incus/instance_logs.go
incus/instances.go
test/extras/stresstest.sh
test/suites/backup.sh
test/suites/basic.sh
test/suites/container_devices_proxy.sh
test/suites/filemanip.sh
test/suites/query.sh
test/suites/serverconfig.sh
test/suites/snapshots.sh

With Incus we get a nice clean slate, so remove the compatibility APIs.
Closes #13

Remove /1.0/containers and /1.0/virtual-machines aliases

---

.github/ISSUE_TEMPLATE.md
client/connection.go
inc/config_trust.go
inc/export.go
inc/file.go
inc/image.go
inc/import.go
inc/manpage.go
inc/storage_volume.go
incus/apparmor/archive.go
incus/apparmor/instance.go
incus/apparmor/instance_forkproxy.go
incus/apparmor/instance_qemu.go
incus/apparmor/network_dnsmasq.go
incus/apparmor/network_forkdns.go
incus/apparmor/qemuimg.go
incus/apparmor/rsync.go
incus/device/device_utils_unix.go
incus/device/disk.go
incus/device/proxy.go
incus/instance/drivers/driver_lxc.go
incus/network/acl/driver_common.go
incus/network/openvswitch/ovn.go
incus/project/permissions.go
incus/storage/drivers/driver_btrfs.go
incus/storage/drivers/driver_cephobject_buckets.go
incus/storage/drivers/driver_dir.go
incus/storage/drivers/driver_lvm.go
shared/network_unix.go
shared/util.go

Remove snap handling logic

---

incus/api_1.0.go
incus/daemon.go
incus/device/config/device_runconfig.go
incus/instance/drivers/driver_lxc.go
incus/main_checkfeature.go
incus/main_forkmount.go
incus/main_forksyscall.go
incus/seccomp/seccomp.go
incus/storage/drivers/utils.go
incus/sys/os.go
shared/idmap/shift_linux.go
test/suites/container_devices_disk.sh
test/suites/security.sh

Remove shiftfs

---

incus/networks.go

incus: fix typo in networks.go

---

doc/environment.md
incusd/instance/instance_utils.go
test/suites/security.sh

Remove INCUS_UNPRIVILEGED_ONLY

---

cmd/lxd-to-incus/db.go

In case snapshots are already uncompressed, don't try to uncompress them.

cmd/lxd-to-incus: Don't try to uncompress non-compressed snapshots

---

.github/workflows/tests.yml

It seems that main has introduced issues that need to be addressed.

tests: Switch to stable cowsql PPA

---

cmd/incus/admin.go
cmd/incus/admin_shutdown.go
cmd/incus/admin_sql.go
cmd/incus/admin_waitready.go
incusd/api_internal.go
incusd/main.go
incusd/main_sql.go
internal/sql/struct.go
test/extras/stresstest.sh
test/includes/incusd.sh
test/suites/backup.sh
test/suites/clustering.sh
test/suites/clustering_instance_placement_scriptlet.sh
test/suites/clustering_move.sh
test/suites/container_devices_proxy.sh
test/suites/image.sh
test/suites/network_zone.sh
test/suites/snapshots.sh
test/suites/sql.sh
test/suites/warnings.sh

Move some more commands to `incus admin`:
- `incus admin shutdown`
- `incus admin waitready`
- `incus admin sql`

Move incusd commands into incus admin

---

incusd/main.go
incusd/main_waitready.go

Add the command back as a hidden command as it's used by the server's init scripts.

incusd: Re-introduce waitready

---

cmd/lxd-to-incus/main.go
cmd/lxd-to-incus/sources.go
cmd/lxd-to-incus/sources_deb.go
cmd/lxd-to-incus/sources_snap.go
cmd/lxd-to-incus/targets.go

This PR handles:
- Migrating from Debian 12 lxd .deb
- Migrating LXD <= 5.18
- Proper handling of existing Incus package
- Rewrite of storage pool sources
- Validate network configuration
- Validate instance/profile configuration
- Check that we're not clustered
Closes #115

lxd-to-incus improvements

---

cmd/incus-user/main_daemon.go
cmd/incus-user/proxy.go
cmd/incus-user/server.go
shared/cliconfig/remote.go
shared/util/filesystem_unix.go
shared/util/filesystem_windows.go

This will make all Incus commands now understand the unprivileged socket and attempt to connect through it when the privileged socket isn't available.

Add support for incus-user to shared/cliconfig

---

README.md

README: Fix link to getting started

---

.github/workflows/tests.yml

github: Build static binaries for x86_64 and aarch64

---

cmd/incus/admin_cluster.go

cmd/incus/admin_cluster: Fix re-exec logic

---

.github/workflows/tests.yml
cmd/lxd-to-incus/go.mod
cmd/lxd-to-incus/go.sum
go.mod
go.sum

Update to get the newer x/net which addresses the HTTP/2 rapid reset bug.

gomod: Update dependencies

---

internal/server/seccomp/seccomp.go

internal/server/seccomp: Fix clang build

---

.github/workflows/tests.yml
internal/server/instance/drivers/driver_qemu.go

instance/qemu: Tweak systemd/udev units of incus-agent

---

shared/osarch/architectures.go

shared/osarch: Add loongarch64

---

doc/internals.md
doc/packaging.md

doc: Add packaging instructions

---

cmd/lxd-to-incus/main.go
cmd/lxd-to-incus/ovn.go
cmd/lxd-to-incus/validate.go

A number of bugfixes and improvements that came about from a recent large cluster migration from LXD to Incus.

lxd-to-incus bugfixes

---

doc/.wordlist.txt
doc/installing.md

As requested. :)
I'll also have an alternative installation for the Mac client once I get the incus client portion refactored in nixpkgs.

doc/installing: init NixOS instructions

---

Makefile
cmd/lxd-to-incus/go.mod
cmd/lxd-to-incus/go.sum
go.mod
go.sum
internal/server/auth/driver_openfga.go
test/mini-oidc/go.mod
test/mini-oidc/go.sum
test/mini-oidc/main.go

Bump OpenFGA to 0.3.1

---

internal/server/instance/drivers/driver_qemu.go

incusd/instances/qemu: Don't fail event sending on missing agent

---

cmd/lxd-to-incus/validate.go

lxd-to-incus: Clarify error messages

---

doc/explanation/clustering.md
doc/howto/cluster_form.md
doc/installing.md
doc/reference/storage_ceph.md

doc/installing: Fix chocolatey link

---

cmd/lxd-to-incus/sources_snap.go

lxd-to-incus: Support alternative snap path

---

cmd/incusd/networks.go

incusd/networks: Don't Fill network configs when joining

---

cmd/incus/create.go

incus/create: Set Target after network/storage lookup

---

cmd/incusd/storage_pools.go

incusd/storage_pools: Don't crash on nil pool

---

internal/server/instance/drivers/driver_qemu.go

incusd/instance/qemu: Don't hardcode UEFI firmware in checkFeatures

---

cmd/incus/project.go

incus/project: Get current project from connection info

---

cmd/incusd/migrate_instance.go

incusd/migration: Properly forward errors

---

shared/archive/archive.go

internal/archive: Fix squashfs error handling

---

scripts/bash/incus

scripts/bash: Don't follow aliases

---

cmd/incus-agent/templates.go
doc/api-extensions.md
doc/reference/image_format.md
doc/rest-api.yaml
internal/server/instance/drivers/driver_lxc.go
internal/version/api.go
shared/api/image.go

Add support for template file uid/gid/mode

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
cmd/incusd/main_checkfeature.go
internal/server/apparmor/instance.go
internal/server/apparmor/instance_lxc.go
internal/server/instance/drivers/driver_lxc.go
internal/server/sys/os.go

Add support for unprivileged binfmt_misc

---

cmd/incus/completion.go
cmd/incus/config.go

incus/config: add completions

---

cmd/incus/completion.go
cmd/incusd/patches.go
doc/reference/storage_lvm.md
internal/server/db/storage_pools.go

Make lvm.vg.force_reuse server-specific

---

internal/server/device/disk.go

incusd/device/disk: Fix incorrect block volume usage

---

internal/server/instance/drivers/driver_qemu.go

incus/instance/qemu: Fix RecordOutput

---

internal/server/network/driver_bridge.go

incusd/network/bridge: Set local address on all VXLAN tunnels

---

cmd/incusd/daemon.go
internal/server/device/nic_ovn.go
internal/server/network/network_utils_bridge.go
internal/server/network/ovn/ovn_icsb.go
internal/server/network/ovn/ovn_nb_actions.go
internal/server/network/ovs/ovs_actions.go

This one ports some of the most common OVS interactions to OVSDB.
On top of that, it fixes the ICSB using the wrong schema and introduces a couple of bits needed for the OVN IC work.

More OVSDB work

---

internal/server/project/project.go

Fix config name in ImageProjectFromRecord

---

cmd/incus/cluster.go
cmd/incus/cluster_group.go
cmd/incus/cluster_role.go
cmd/incus/completion.go
cmd/incus/config_device.go
cmd/incus/config_metadata.go
cmd/incus/config_template.go
cmd/incus/list.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

- **incus: add completions for clusters**
- **incus: add completions for cluster groups**
- **incus: add completions for cluster roles**
- **incus: add completions for config devices**
- **incus: add completions for config templates**

incus: add more completions

---

shared/idmap/set_load.go

shared/idmap: Support uid/gid in subuid/subgid

---

cmd/incus/completion.go
cmd/incus/network_forward.go
cmd/incus/network_load_balancer.go

- **incus: add completions for network forwards**
- **incus: add completions for network load balancers**
I don't have OVN so I can't test the load balancer subcommand.

add completions for network forward and load balancers

---

cmd/incus/admin_init_auto.go

incus/admin/init: Use btrfs subvol in --auto

---

cmd/incus-migrate/main_migrate.go

incus-migrate: Clarify that disk image files must be raw

---

cmd/incusd/api_project.go
doc/config_options.txt
internal/server/metadata/configuration.json
internal/server/network/ovn/ovn_icnb_actions.go

Moving those separately to reduce commit count in the OVN IC branch.

Bugfixes from OVN IC branch

---

doc/cloud-init.md

doc/cloud-init: Update network example to v2

---

doc/explanation/storage.md

doc/storage: Clarify remote storage

---

cmd/incus/info.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Adds detailed system information to the output of incus info --resources, addressing issue #705.

Implement System Information Display for incus info --resources

---

cmd/incus/snapshot.go

incus/snapshot: Fix deletion of snapshots containing colons

---

cmd/incus/project.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/project: Add yaml support for project create

---

cmd/incus/snapshot.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Add yaml support for snapshot create

---

cmd/incus/cluster_group.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/cluster_group: Add yaml support for cluster group create 

---

cmd/incus/info.go

incus/info: Sorting network interfaces

---

cmd/incus/network_integration.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/network_integrations: Add yaml support for create

---

doc/.sphinx/requirements.txt

Fixes the Sphinx build regression.

doc: Avoid MyST 3.0.0

---

cmd/incus/project.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Add customizable columns to project list command
This fixes issue #717

incus/project: Add customizable column list

---

internal/server/instance/drivers/driver_qemu.go

incusd/instances/qemu: Tweak secureboot firmware list

---

cmd/incus/storage_volume.go

incus/storage_volume: Clarify volume errors

---

doc/api-extensions.md
doc/howto/network_acls.md
internal/server/network/acl/acl_firewall.go
internal/server/network/acl/acl_ovn.go
internal/server/network/acl/driver_common.go
internal/version/api.go

Issue 651: Add support for stateless rules in network ACLs

---

shared/archive/archive.go

shared/archive: Properly anchor exclude rules

---

internal/server/project/permissions.go

incusd/project: Rework low-level permission checks

---

doc/config_options.txt
doc/image-handling.md
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/metadata/configuration.json

Replaces hard coded key values for image restrictions with automated generated ones.
Closes https://github.com/lxc/incus/issues/820

Added generated documentation for image restrictions. 

---

cmd/incus/storage_bucket.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/storage_bucket: Add yaml support for key create

---

doc/config_options.txt
doc/reference/instance_options.md
internal/instance/config.go
internal/server/metadata/configuration.json

doc: Add generated documentation for instance kernel limits

---

doc/config_options.txt
doc/reference/devices_usb.md
internal/server/device/usb.go
internal/server/metadata/configuration.json

doc: Add generated documentation for USB devices

---

doc/config_options.txt
doc/reference/devices_unix_block.md
doc/reference/devices_unix_char.md
doc/reference/devices_unix_hotplug.md
internal/server/device/unix_common.go
internal/server/device/unix_hotplug.go
internal/server/metadata/configuration.json

Replaces hardcoded key values for unix devices as stated in #824

Added generated documentation for Unix devices #824

---

doc/config_options.txt
doc/howto/network_zones.md
internal/server/metadata/configuration.json
internal/server/network/zone/zone.go

Add generated documentation for network zones 

---

cmd/incus/network.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

closes Add customizable columns to incus network list #719 
signed off by: Joshua Dierker <joshuadierker@gmail.com>

Add customizable columns network list functionality 

---

internal/server/instance/drivers/driver_common.go

incusd/instance: Fix building on 32bit architectures

---

cmd/incus/network_zone.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/network_zone: Add example for network zone record create

---

cmd/incus-simplestreams/main_add.go

incus-simplestreams: add --no-default-alias and --alias

---

internal/server/storage/drivers/driver_btrfs_volumes.go

incusd/storage/btrfs: Fix btrfs argument order

---

internal/server/seccomp/seccomp.go
internal/server/seccomp/sysinfo.go
internal/server/seccomp/sysinfo_32.go
internal/server/seccomp/sysinfo_64.go

incusd/seccomp/sysinfo: Handle 32bit on 64bit

---

doc/howto/instances_console.md

doc/instances_console: Tweak wording on SPICE clients

---

internal/server/apparmor/instance_forkproxy.go

incusd/apparmor: Allow /dev/shm in forkproxy

---

doc/installing.md

doc/installing: Mention incus-tools package

---

cmd/incusd/profiles.go

incusd: Improve profile rename errors

---

cmd/incus-user/server.go

incus-user: Use shorter interrface name for long UIDs

---

internal/server/apparmor/qemuimg.go
internal/server/apparmor/qemuimg_test.go
internal/server/storage/utils.go

The benefit is no extra go routine wait and sleep, code clean and easy to read(an surplus err return has been removed).

Use qemu-img convert output to update progress

---

doc/howto/incus_alias.md

Expanded the howto to cover all alias subcommands, the built-in alias, non-root shell.

doc: Update incus_alias.md

---

internal/server/network/driver_ovn.go

incusd/network/ovn: Require functional uplink

---

doc/howto/instances_create.md

Added instructions on how to install the incus agent manually.

doc/instances: Cover incus agent installation

---

doc/.wordlist.txt
doc/clustering.md
doc/howto/cluster_access.md

doc/clustering: Add howto on cluster access

---

cmd/incus/image_alias.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Added the flag --column to ```image alias list```for issue #1027

incus/image/alias: Add column flag

---

cmd/incus/cluster_group.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Cluster group list add column flag

---

internal/server/storage/utils.go

incusd/storage: Fix UsedBy values for sub-directory volumes

---

client/doc.go

Woops 🙈
Follows https://github.com/lxc/incus/pull/1104

client: fix typo

---

doc/.wordlist.txt
doc/api-extensions.md
doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/metadata/configuration.json
internal/server/project/permissions.go
internal/version/api.go

This PR allows to inject QMP commands at various stages of a VM initialization

Add support for manual QMP configuration

---

cmd/incusd/main_forknet.go

Add DHCP Option 12 hostname to dhcp request on instance init.

incusd/forknet_dhcp: Add hostname to dhcp request

---

cmd/incus/network_peer.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Network peer list add column flag

---

cmd/incus/network_load_balancer.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Network load balancer list add column flag

---

client/incus_instances.go

client: Fix error handling in push mode copy

---

internal/server/instance/drivers/edk2/driver_edk2.go

@stgraber Sorry for the mess. This is still pending the qemu path issue.

incusd/instance/edk2: Add Void Linux x86_64 paths

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/seccomp/seccomp.go

Various bugfixes

---

cmd/incus-user/main_daemon.go
cmd/incus-user/proxy.go
cmd/incus-user/server.go

Add logic to keep track of the available projects and if the user's project is missing, re-create it automatically.
Closes #1149

incus-user: Handle deleted projects

---

internal/server/storage/drivers/driver_zfs_volumes.go

incusd/storage/zfs: Make sure the zvol is a block device

---

doc/installing.md

Adds link to Arch Linux Wiki for Incus.

doc/installing: Add link to Arch Wiki for Incus

---

cmd/incus/console.go

incus/console: Add completion

---

internal/server/instance/drivers/driver_qemu.go

incusd/instance/qemu: Properly plumb I/O limits

---

client/incus_network_load_balancers.go
client/interfaces.go
cmd/incus/network_load_balancer.go
cmd/incusd/api_1.0.go
cmd/incusd/network_load_balancers.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/network/driver_common.go
internal/server/network/driver_ovn.go
internal/server/network/network_interface.go
internal/server/network/ovn/ovn_sb_actions.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/network_load_balancer.go

Add OVN load balancer state API

---

client/oci_images.go

client: Capture original OCI image identifier

---

doc/api-extensions.md
doc/reference/storage_lvm.md
internal/server/storage/drivers/driver_lvm.go
internal/version/api.go
shared/subprocess/run.go

Allow fully creating LVM cluster pools through the API

---

internal/server/network/ovn/ovn_icsb_actions.go
internal/server/storage/drivers/driver_ceph_volumes.go
internal/server/storage/drivers/driver_lvm_volumes.go
internal/server/storage/drivers/driver_zfs_volumes.go

The intention here should be to initialize a slice with a capacity of length rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

cmd/incus-agent/state.go

incus-agent: Add timeout for DNS query

---

internal/server/network/driver_ovn.go

- Accept a new parameter `ipv4.dhcp.ranges` that will add new entries to OVN `exclude_ips`

incusd/network/ovn: Add support to ipv4.dhcp.ranges

---

internal/server/instance/drivers/driver_qemu.go

incusd/instance/qemu: Log QEMU command line

---

cmd/incus/file.go

Part of  #1176. 
Please let me know if any changes needed.

incus/file/create: Use SFTP client instead of file API

---

cmd/incus/top.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Adds support for following options:
- `--format` - possibility to define output format
- `--columns` - possibility to define column layout
- `--refresh` - possibility to configure the refresh delay
Closes: #1028

Make `incus top` output configurable through options

---

cmd/incus/main.go
cmd/incus/main_aliases.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/cliconfig/file.go

This PR also improves the configuration loading because I didn't want to copy/paste on more time the code used to locate the user configuration file.

incus: Add aliases completion

---

internal/server/task/group.go

Suggested-by: Lucas Bremgartner <lucas.bremgartner@futurfusion.io>

incusd/task: Fix wait group logic (more entries than running tasks)

---

cmd/incusd/daemon_storage.go

incusd/daemon_storage: Ensure corect symlinks for images/backups

---

internal/server/storage/drivers/driver_lvm_utils.go

incusd/storage/lvm: Handle newer LVM

---

doc/.wordlist.txt
doc/installing.md

These instructions are kind of simple, let me know if you want me to include more details.

doc: add openSUSE installation instructions

---

cmd/incus/project.go

Closes #1474 
**First contribution to opensource sorry if I missed some of the best practices**

incus/project: Fix handling of default (unset) project in `get-current`

---

cmd/incusd/api_cluster.go

incusd/cluster: Skip project restrictions during join

---

client/incus_instances.go
cmd/incusd/main_forkfile.go

This should allow for much better performance in file transfers now that we're moving more and more of our logic to SFTP.

Improve SFTP performance

---

cmd/incusd/instance_post.go

incusd/instance_post: Expand profiles in scriptlet context

---

doc/reference/instance_options.md
internal/server/scriptlet/load/load.go

Fix QEMU scriptlet parameter name

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/commands.go

I was genuinely worried it would be harder
Closes: #1522

incusd/instance/qemu: Fix QMP arguments typing

---

internal/server/network/driver_ovn.go

internal/server: allow creation of OVN network with no uplink

---

internal/server/dnsmasq/dnsmasq.go

incusd/dnsmasq: Don't put the project name in the DNS record

---

cmd/incus/file.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

incus/file/pull Use SFTP client instead of file API

incus/file/pull: Port to SFTP

---

doc/.sphinx/_static/swagger-override.css

doc: Force white background for swagger API

---

internal/server/instance/drivers/qmp/monitor.go

incusd/instance/drivers/qmp: Handle missing log directory

---

.github/workflows/tests.yml
cmd/incus/file.go

incus/file/pull: Ensure we have a leading / in all paths

---

doc/installing.md

It is possible since https://github.com/NixOS/nixpkgs/pull/355645.

doc/installing: mention incus group on NixOS

---

internal/server/network/driver_ovn.go

incus/network/info (ovn): Fix object not found.

---

shared/archive/detect.go

Fixes #1610 
I need to actually test it. I cannot retrieve where, in the import process, the backup_file is decompressed, any hint would be appreciated :).

Added LZ4 support for incus import

---

internal/cmd/table.go

Update --format validation to provide more information.

list/format: provide more information on error

---

cmd/incusd/api_cluster.go

1. Prevent generating a join token for a member if one already exists in the cluster.
2. Before adding a new member, check if a member with the same name already exists in the cluster.
Fixes: #1636

Add additional validation when joining a new cluster member

---

cmd/incusd/instance_file.go
test/suites/filemanip.sh

Ensure directories have 755 permissions in `incus file push -p` command

---

cmd/incus/file.go

incus/file: Port remaining functions to SFTP

---

internal/server/storage/drivers/utils_ceph.go

incusd/storage/ceph: Re-introduce keyring parsing

---

doc/.wordlist.txt
doc/api-extensions.md
doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/metadata/configuration.json
internal/version/api.go

Move IOMMU handling under configuration option

---

doc/requirements.md

doc: Clarify virtiofsd requirements

---

doc/config_options.txt
internal/instance/config.go
internal/server/metadata/configuration.json

See https://github.com/lxc/incus-os/issues/15

Clarify security.secureboot setting

---

cmd/incusd/instance.go

Fix revert on OCI container creation failure

---

internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go

Fixes #1737.
I think OCI containers can't profit from this (yet) because the forknet dhcp client exits if it encounters any errors.

Configure DHCP on existing instance interfaces when it is enabled on a network

---

cmd/incusd/certificates.go

incusd/certificates: Properly handle bad PEM data

---

internal/server/instance/drivers/driver_lxc.go

incusd/instance/lxc: Cleanup OCI mount paths

---

internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go

incusd/instance: Don't enforce device/config validation on snapshots

---

doc/reference/storage_linstor.md

Signed-off-by: Luís Simas <luis.nascimento@luizalabs.com>

doc: Fix config option reference on LINSTOR driver

---

cmd/lxd-to-incus/main.go

Closes https://github.com/zabbly/incus/issues/78

lxd-to-incus: Fix typo in trigger

---

doc/authentication.md

doc: Tweak ACME documentation

---

internal/server/instance/drivers/driver_qemu.go

Replace deprecated `-runas` with supported `-run-with user` parameter for QEMU versions 9.1 and above.
Closes: #1870

instances/drivers/qemu: update user parameter for QEMU v9.1+

---

cmd/incusd/storage_volumes_snapshot.go

incusd/storage: Add missing forwarding on snapshot list

---

cmd/incus-agent/events.go

incus-agent: Retry mounts to avoid kernel races

---

cmd/incusd/api_project.go
doc/config_options.txt
internal/server/cluster/config/config.go
internal/server/metadata/configuration.json

Update list of compresors

---

cmd/incusd/api.go
cmd/incusd/api_os.go

For now we're requiring equivalent permissions to full admin on Incus.

incusd: Implement Incus OS API forwarding

---

doc/config_options.txt
doc/howto/network_forwards.md
internal/server/metadata/configuration.json
internal/server/network/driver_common.go

Resolves #1785
Signed-off-by: Tony Nguyen <tonynguyen10@utexas.edu> and Anthony Rojas <anthony.rojas@utexas.edu>

Add generated documentation for network forwards

---

doc/config_options.txt
doc/reference/devices_tpm.md
internal/server/device/tpm.go
internal/server/metadata/configuration.json

Resolves issue [#1791 ](https://github.com/lxc/incus/issues/1791)
Signed-off-by: Saahir Narang <saahir.narang@gmail.com>, Harshadeep Kambhampati <harshadeepk02@gmail.com>

Port tpm device documentation to gendoc

---

cmd/incusd/devices.go
cmd/incusd/instances_post.go

incusd/devices: Don't require a serial number for USB hotplug

---

internal/server/auth/authorization_objects_test.go
internal/server/cluster/gateway_test.go
internal/server/cluster/heartbeat_test.go
internal/server/cluster/membership_test.go
internal/server/cluster/notify_test.go
internal/server/cluster/upgrade_test.go
internal/server/endpoints/endpoints_test.go
internal/server/endpoints/network_test.go
shared/tls/cert.go
shared/tls/tlstest/tlstest.go

So that the testing logic not build in release binary

Move tls testing functions to tlstest

---

doc/config_options.txt
doc/reference/devices_proxy.md
internal/server/device/proxy.go
internal/server/metadata/configuration.json

Resolves #1790
Signed-off-by: Abdulrahman Alshahrani <abdulrahmanalshahrani@utexas.edu>

Port `proxy` device documentation to `gendoc`

---

doc/config_options.txt
doc/reference/devices_gpu.md
internal/server/device/gpu_mdev.go
internal/server/device/gpu_mig.go
internal/server/device/gpu_physical.go
internal/server/device/gpu_sriov.go
internal/server/metadata/configuration.json
shared/tls/cert.go

Port gpu device documentation to gendoc

---

doc/config_options.txt
doc/reference/devices_nic.md
internal/server/device/nic_bridged.go
internal/server/device/nic_ipvlan.go
internal/server/device/nic_macvlan.go
internal/server/device/nic_ovn.go
internal/server/device/nic_p2p.go
internal/server/device/nic_physical.go
internal/server/device/nic_routed.go
internal/server/device/nic_sriov.go
internal/server/metadata/configuration.json

Port nic device documentation to gendoc

---

internal/server/storage/backend.go

incusd/storage/migration: Check instance size during migration

---

internal/server/device/disk.go

Closes #1979
Suggested-by: gwenya

incusd/device/disk: Fix registration of custom volumes

---

internal/server/scriptlet/instance_placement.go

in case of invalid member name

scriptlet: Return proper error

---

internal/server/instance/drivers/util.go

The cache logic changed at some point and doesn't include the local server. This is pretty reasonable but we need to make sure to get our own local data when needed.
Reported-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>

incusd/instance: Also consider local CPU flags

---

internal/server/firewall/drivers/drivers_consts.go
internal/server/firewall/drivers/drivers_nftables.go

Apparently nftables isn't very consistent on field typing which is causing issues, so let's simplify that logic as much as possible.

Fix issues with nftables and address sets

---

doc/config_options.txt
doc/reference/devices_infiniband.md
doc/reference/devices_pci.md
doc/reference/devices_tpm.md
internal/server/device/device_load.go
internal/server/device/infiniband_physical.go
internal/server/device/pci.go
internal/server/device/tpm.go
internal/server/metadata/configuration.json

Added gendoc comments to validater in devices/pci
generated new config metadata
updated documentation to use new gernerated metadata

Port pci to gendoc

---

client/incus_images.go
cmd/incus/copy.go
cmd/incus/file.go
cmd/incusd/instance_post.go
internal/linux/filesystem.go
internal/server/auth/driver_tls.go
internal/server/device/device_utils_network.go
internal/server/endpoints/cluster.go
internal/server/endpoints/metrics.go
internal/server/endpoints/network.go
internal/server/firewall/firewall_load.go
internal/server/instance/drivers/qmp/commands.go
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go
shared/archive/archive.go

This PR refactors a few condition checks where the whole condition or a part of the condition is known to be true or false  at compile time/static analysis time.

Refactor unnecessary if checks

---

doc/config_options.txt
doc/reference/network_bridge.md
doc/reference/network_physical.md
internal/server/metadata/configuration.json
internal/server/network/driver_bridge.go
internal/server/network/driver_physical.go

We have updated the code, please let us know if there needs to be any style changes or fixes in general. We also have made changes to network_physical as requested.
Closes #1795

Update gendoc for network_physical and network_bridge

---

internal/server/storage/backend.go

Adds assigning an err to the result of a transaction where it was forgotten.

incusd: add missing err handling for transactions

---

internal/server/storage/drivers/driver_zfs_volumes.go

incusd/storage/zfs: Optimize snapshot deletion

---

cmd/generate-config/incus_doc.go
cmd/incusd/api_internal.go
cmd/incusd/api_internal_recover.go
cmd/incusd/api_internal_test.go
cmd/incusd/instance.go
cmd/incusd/patches.go
cmd/lxc-to-incus/main_migrate_test.go
internal/server/db/cluster/update.go
internal/server/firewall/drivers/drivers_nftables.go
internal/server/network/acl/acl_ovn.go
internal/server/network/driver_common.go
internal/server/network/ovn/ovn_nb_actions.go

This PR removes the redundant map size 0 initialization in a bunch of places.

Remove redundant map size

---

internal/server/dns/server.go

Closes #1999 
I'm not completely certain about this implementation, a thorough review is appreciated.
I went with this approach with the "controller" goroutine that handles start/stop/restart/reconfigure commands because my previous attempt (https://github.com/gwenya/incus/tree/dns-restart) kept running into deadlock and correctness issues.

Restart builtin DNS server on failure

---

cmd/generate-database/db/parse.go
cmd/generate-database/db/stmt.go
cmd/generate-database/lex/form.go

Some additional fixes to make `generate-database` play nicely with more complex cases.

Db generate fixes

---

internal/server/instance/drivers/driver_qemu_config_test.go
internal/server/instance/drivers/driver_qemu_templates.go

incusd/instance/qemu: Limit memory hotplug slots to 8

---

cmd/incusd/daemon.go
internal/server/instance/drivers/util.go

Created the new function getNodeResources()
1. Added a new parameter s *state.State from the original instructions provided. This takes care of checking if cache is recent(less than 24hrs) and getting the data if it's missing or discarded for both local and remote nodes. 
2. Removed the old logic from daemon.go where it uses heartbeatHandler to update cache.

Move cluster resource caching to point of consumption 

---

cmd/incus/admin_init_interactive.go
cmd/incus/cluster.go
cmd/incus/cluster_group.go
cmd/incus/config.go
cmd/incus/config_device.go
cmd/incus/copy.go
cmd/incus/create.go
cmd/incus/file.go
cmd/incus/list.go
cmd/incus/list_test.go
cmd/incus/main_aliases.go
cmd/incus/move.go
cmd/incus/network.go
cmd/incus/network_acl.go
cmd/incus/network_address_set.go
cmd/incus/network_forward.go
cmd/incus/network_integration.go
cmd/incus/network_load_balancer.go
cmd/incus/network_peer.go
cmd/incus/network_zone.go
cmd/incus/profile.go
cmd/incus/project.go
cmd/incus/storage.go
cmd/incus/storage_bucket.go
cmd/incus/storage_volume.go
cmd/incus/utils.go
cmd/incus/utils_properties.go

Using more modern features of Go, such as:
- conditional assignment -> built-in min or max in go1.21,
- sort.Slice -> slices.Sort in go1.21,
- loop assign map -> maps.Copy in go1.21,
- []byte(fmt.Sprintf...) -> fmt.Appendf(nil,...) in go1.19,
- strings.HasPrefix / strings.TrimPrefix -> strings.CutPrefix in go1.20

incus: Simplify code by using modern constructs

---

cmd/generate-config/incus_doc.go
cmd/generate-database/db.go
cmd/generate-database/db/parse.go
cmd/incus-agent/dev_incus.go
cmd/incus-agent/events.go
cmd/incus-agent/exec.go
cmd/incus-agent/main_agent.go
cmd/incus-agent/os_linux.go
cmd/incus-benchmark/benchmark_batch.go
cmd/incusd/api_cluster_evacuation.go
cmd/incusd/api_internal.go
cmd/incusd/api_metrics.go
cmd/incusd/certificates.go
cmd/incusd/daemon_config.go
cmd/incusd/devices.go
cmd/incusd/images.go
cmd/incusd/instance_exec.go
cmd/incusd/instance_post.go
cmd/incusd/instance_test.go
cmd/incusd/instances.go
cmd/incusd/instances_get.go
cmd/incusd/instances_post.go
cmd/incusd/migrate_storage_volumes.go
cmd/incusd/networks.go
cmd/incusd/networks_utils.go
cmd/incusd/storage_pools.go
cmd/lxc-to-incus/config.go

Using more modern features of Go, such as:
- conditional assignment -> built-in min or max in go1.21,
- sort.Slice -> slices.Sort in go1.21,
- loop assign map -> maps.Copy in go1.21,
- []byte(fmt.Sprintf...) -> fmt.Appendf(nil,...) in go1.19,
- strings.HasPrefix / strings.TrimPrefix -> strings.CutPrefix in go1.20

Simplify code by using modern constructs

---

cmd/incusd/instance_post.go

incusd/instances: Tweak storage migration errors

---

internal/server/instance/drivers/util.go

incusd/instance: Fix incorrect cluster.Connect call

---

cmd/incusd/instances_post.go

incusd/instances_post: Prevent pointless device overrides

---

internal/server/instance/drivers/qmp/monitor.go
internal/server/instance/drivers/qmp/qmp.go

incusd/instance/qmp: Refactor qmpWriteMsg

---

internal/server/storage/drivers/driver_zfs_volumes.go
internal/server/storage/drivers/volume.go
shared/api/resource.go

While working on a separate large pull-request I came across a few trivial typos

incusd: fix some trivial typos

---

client/incus_cluster.go
client/interfaces.go
cmd/incusd/api_cluster.go
internal/server/cluster/membership.go
internal/server/cluster/membership_test.go
internal/server/db/node.go

Remove pending cluster member on join failure

---

internal/server/storage/drivers/driver_linstor.go
test/includes/clustering.sh
test/suites/clustering.sh

incusd/storage/linstor: Prevent mounting unreachable pools

---

internal/server/instance/drivers/qmp/monitor.go
internal/server/instance/drivers/qmp/qmp.go
internal/server/instance/drivers/qmp/qmp_test.go

Use net UnixConn only and refactor unit test cases

incusd/instance/qmp remove net Conn

---

internal/server/instance/drivers/driver_lxc.go

incusd/instance/lxc: Tweak OCI entrypoint escaping

---

internal/server/storage/backend.go

incusd/storage: Handle missing storage bucket listener

---

internal/server/device/disk.go

incusd/device/disk: Allow degraded zpools

---

internal/server/ip/link.go
internal/server/ip/route.go

See  #1990
@stgraber can you try these and see if they fix the issues?

Fixes for netlink 

---

cmd/incus/remote.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

Add support for the `keepalive` flag in the CLI.
Closes: #2247

incus/remote: Support keepalive flag

---

cmd/incusd/dev_incus.go

We shouldn't just rely on the process name but also make sure that it's running outside of the container as this is a unique characteristic of the real monitor process.

incusd/dev_incus: Add extra validation for monitor

---

internal/server/db/cluster/networks_peers.go
test/main.sh
test/suites/network_peers.sh

Fix network peering 

---

doc/howto/instances_create.md

doc/instances_create: Extend the Incus VM agent instructions

---

internal/server/network/driver_bridge.go

This is for a bit of an edge case related to planned use by Incus OS.
Basically we want to be able to have an Incus cluster with an internal IPv6 network which is connected through multicast VXLAN.
In that scenario each individual server will be acting as a router emitting RAs. For proper operation we need each server to have its own MAC address and we need a way to avoid duplicate host addresses.
For that reason, we're now making two changes:
- Require a machine specific MAC address when tunnels are used
- Support automatically deriving (EUI64) a local IPv6 address when provided with an address-less /64 IPv6 subnet.

incusd/network/bridge: Allow automatic host-specific IPv6 addresses

---

internal/server/device/nic_physical.go
internal/server/instance/drivers/driver_qemu.go

Set MAC address for physical NIC with bridge parent

---

cmd/incus/config_template.go
cmd/incus/snapshot.go
cmd/incus/storage_volume.go

Some alias to list command were missing for some of the cli commands.

Some command alias for list / ls were missing

---

internal/server/device/device_utils_disk.go

incusd/device/disk: Enable posix ACL support for virtiofsd

---

internal/server/storage/backend.go
internal/server/storage/drivers/driver_btrfs_volumes.go
internal/server/storage/drivers/driver_ceph_volumes.go
internal/server/storage/drivers/driver_cephfs_volumes.go
internal/server/storage/drivers/driver_dir_volumes.go
internal/server/storage/drivers/driver_linstor_volumes.go
internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go
internal/server/storage/drivers/driver_zfs_volumes.go
internal/server/storage/drivers/generic_vfs.go
internal/server/storage/drivers/volume.go

incusd/storage: Fix EnsureMountPath to avoid resetting permissions

---

internal/server/network/driver_common.go

incusd/server/network: Fix update config regression

---

internal/server/network/driver_bridge.go

incusd/network/bridge: Don't require dnsmasq on link-local IPv6

---

doc/.wordlist.txt
doc/api-extensions.md
doc/explanation/storage.md
doc/reference/storage_drivers.md
doc/reference/storage_truenas.md
internal/server/storage/drivers/driver_truenas.go
internal/server/storage/drivers/driver_truenas_utils.go
internal/server/storage/drivers/driver_truenas_volumes.go
internal/server/storage/drivers/load.go
internal/version/api.go
test/README.md
test/backends/truenas.sh
test/includes/clustering.sh
test/includes/storage.sh
test/main.sh
test/suites/backup.sh
test/suites/basic.sh
test/suites/clustering.sh
test/suites/container_move.sh
test/suites/migration.sh
test/suites/snapshots.sh
test/suites/storage.sh
test/suites/storage_driver_truenas.sh
test/suites/storage_local_volume_handling.sh
test/suites/storage_snapshots.sh

Implement TrueNAS storage driver

---

cmd/incusd/main_forknet.go

The built-in DHCPv4 client used for OCI containers can overwhelm the DHCP server with renewals every 60 seconds. This occurred when the initial DHCPOFFER lacked renewal/rebind timers (Options 58/59). The renewal loop slept using IPAddressRenewalTime(time.Minute), so the fallback value (1 minute) was used repeatedly.
Additionally, the initial request implicitly asked for a fixed lease time (Option 51) and did not include a Parameter Request List for 51/58/59. Many servers respond by honoring the client’s requested lease (e.g., 3600s) and omitting 58/59 in the OFFER/ACK. Together, these two behaviors produced one-minute renewals even when the server was configured for multi-hour leases.
This change fixes the above by:
1. Not requesting a fixed lease in the client message …

incus/dhcp: Explicitly requesting 51/58/59, derive sane T1, add jitter

---

doc/api-extensions.md
doc/reference/devices_disk.md
internal/server/device/disk.go
internal/version/api.go
test/suites/container_devices_disk.sh

 Add tmpfs support for disk devices

---

cmd/incusd/api_cluster.go
cmd/incusd/daemon.go
internal/server/cluster/membership.go
internal/server/db/node.go

Add ability to exclude a server from acting as a database server in a cluster

---

cmd/incusd/storage_pools.go
internal/server/db/storage_pools.go
internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_types.go

Ensure cluster member configs are updated when `SameSource` is true

---

cmd/incusd/api_1.0.go
cmd/incusd/api_metrics.go
cmd/incusd/api_os.go
cmd/incusd/certificates.go
cmd/incusd/networks.go
internal/incusos/api_services.go
internal/incusos/api_system.go
internal/incusos/client.go
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go
internal/server/storage/drivers/driver_ceph.go
internal/server/storage/drivers/driver_cephfs.go
internal/server/storage/drivers/driver_cephobject.go
internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_truenas.go
internal/server/sys/os.go

Add IncusOS client package and additional checks

---

cmd/incusd/api_metrics.go

incusd/metrics: Always include internal metrics
