CONTRIBUTING.md

Minor changes to support the fork moving away from Canonical.

CONTRIBUTING: rename lxd to incus

---

go.mod
go.sum
shared/termios/termios_other.go

Since `golang.org/x/crypto/ssh/terminal` is deprecated, modify it to use `golang.org/x/term`.
- https://pkg.go.dev/golang.org/x/crypto/ssh/terminal
- https://pkg.go.dev/golang.org/x/term

shared/termios: Use golang.org/x/term instead of golang.org/x/crypto/ssh/terminal

---

incusd/instance/drivers/driver_qemu.go
incusd/instance/drivers/driver_qemu_config_test.go
incusd/instance/drivers/driver_qemu_templates.go

This adds support for the LXD virtio-serial device and agent symlink to allow existing virtual machines to function properly when imported into Incus.

incusd/instance/qemu: Support LXD virtual machines

---

cmd/lxd-to-incus/db.go
cmd/lxd-to-incus/go.mod
cmd/lxd-to-incus/go.sum
cmd/lxd-to-incus/main.go

cmd/lxd-to-incus: Uncompress snapshot files in target database

---

go.mod
go.sum

This version (go-cowsql v1.22.0) gets built without disk-mode, which has been disabled in cowsql. Incus was not using that, so no actual change for it.

Bump go-cowsql to v1.22.0

---

client/incus_server.go
client/incus_storage_volumes.go
cmd/incus/storage_volume.go
internal/server/cluster/membership.go
internal/server/device/device_utils_generic.go
internal/server/device/gpu_physical.go

This is a small set of automatically imported commits from the LXD repository.
The tool I wrote for this task can compare the two repositories for changes that haven't made it to Incus yet.
Currently we're looking at a bit over 400 commits to catch up to LXD 5.18.
Making this work involves a lot of path and function/struct rewriting, mostly through a long list of sed patterns, as well as careful review and occasional manual edit of the commits being processed to make sure they make sense and that everything is still buildable.
To make it clear that those commits originated from outside of Incus, the commit message gets a `[lxd-import]` prefix added.

First attempt at importing LXD commits

---

cmd/incusd/instances_get.go

This removes the instance type checks for containers and VMs based on
the route name. Since the route aliases for containers and VMs have been
removed, these checks are obsolete.
With this change, the `Name` field in the `APIEndpoint` struct is not used
anymore. This field could be removed in a future PR as well.

cmd/incusd: Drop instance type check for containers and VMs

---

cmd/incus/admin.go
cmd/incus/admin_recover.go
cmd/incusd/api_internal_recover.go
cmd/incusd/main.go
cmd/incusd/main_recover.go
internal/recover/struct.go
test/suites/backup.sh

This change moves `incusd recover` to `incus admin recover`. A new package internal/recover is also introduced  in this change. The structures used by the internal recover api and the recover command code are moved into a common package(internal/recover).

Move `incud recover` to `incus admin recover`

---

cmd/incusd/devices.go
cmd/incusd/networks_utils.go
doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_lxc.go
internal/server/metadata/configuration.json
scripts/bash/incus
test/suites/storage_volume_initial_config.sh

This option only ever worked on CGroup1 and had quite a few limitations. It's now being replaced by `limits.priority` set directly on the nic devices.
Closes #113

instance: Remove limits.network.priority

---

cmd/incusd/events.go
doc/config_options.txt
doc/howto/network_ovn_setup.md
internal/server/cluster/config/config.go
internal/server/events/internalListener.go
internal/server/loki/loki.go
internal/server/metadata/configuration.json
internal/server/syslog/listener.go
shared/api/event.go
test/suites/syslog.sh

This replaces the OVN event type introduced in LXD 5.18 with a new NetworkACL event type and updates the receiver to filter OVN events to only those about ACL matches.
This logic could in time be applied to iptables/nft too.
Closes #114

Rename EventTypeOVN to EventTypeNetworkACL

---

doc/contributing.md

To avoid duplicate of links to contributing in doc/general.md.

doc: Add start-after to include CONTRIBUTING.md from contributing.md

---

doc/howto/network_create.md

Duplicated since it was moved to howto/network_configure.

doc: Remove "Configure a network section" in howto/network_create

---

doc/authentication.md
doc/howto/cluster_form.md
doc/howto/images_remote.md
doc/howto/initialize.md
doc/howto/projects_confine.md

doc: Remove all mentions of trust passwords

---

test/main.sh
test/suites/backup.sh
test/suites/incus_user.sh
test/suites/syslog.sh

tests: Add incus-user test

---

shared/cliconfig/remote.go

shared/cliconfig: Nicer error on missing socket

---

internal/server/instance/drivers/driver_lxc.go

When a memory limit is applied to an instance and swap is available on the system, the limit should apply to both memory and swap.
Without it, each instance would be allowed to go over the memory limit by as much as the total system swap space.

instance/lxc: Fix swap limit handling

---

cmd/lxd-to-incus/targets.go

systemd supports multiple paths, so rely on its detection logic instead of checking a specific path.

lxd-to-incus: query systemd instead of assuming service file path

---

cmd/lxd-to-incus/targets.go

Added support for OpenRC systems.

cmd/lxd-to-incus: Add OpenRC target support

---

internal/server/auth/driver_tls.go
test/suites/pki.sh

This fixes a regression introduced by LXD when refactoring the auth code ahead of OpenFGA.
The regression was further hidden by an incorrect PKI test.

Fix handling of trusted certs in CA mode

---

internal/server/device/nic_physical.go
internal/server/device/nic_sriov.go

In VMs, the MTU can be set through the agent, so it should always be allowed as a user configurable property.
Reported-at: https://discuss.linuxcontainers.org/t/incus-and-sriov-issue-error-no-value-found-in-sriov/18273/3

incusd/device: The MTU can always be controlled

---

doc/howto/projects_confine.md
doc/metrics.md

Reported-at: https://discuss.linuxcontainers.org/t/incus-error-while-adding-metrics-certificate-into-incus/18278

doc: Update for trust add-certificate

---

cmd/lxd-to-incus/main.go
cmd/lxd-to-incus/ovn.go

lxd-to-incus: Add support for OVN database mangling

---

doc/installing.md

Following the instructions as-written yields:
```
sudo -E PATH=${PATH} LD_LIBRARY_PATH=${LD_LIBRARY_PATH} $(go env GOPATH)/bin/incus --group sudo
Error: unknown flag: --group
```
This is a trivial change, I do not care about copyright, so if there's something wrong with this commit feel free to just commit it elsewhere. 👍

doc: incus -> incusd in build instructions.

---

doc/explanation/containers_and_vms.md

Differences between application/system containers and VMs.

Added text on the difference between containers and VMs

---

internal/server/auth/driver_openfga.go

Without chunking, we quickly hit the limit of 100 operation per transaction.

incusd/auth/openfga: Use chunking

---

doc/installing.md
doc/userns-idmap.md

Link to a Gentoo Wiki's main Incus page will be added once it's created. It'll hold more information, examples, Gentoo-specific use cases and so on.

doc/installing.md: add installation steps for Gentoo

---

internal/server/cluster/heartbeat.go
internal/server/db/backups.go
internal/server/db/cluster/open.go
internal/server/db/db.go
internal/server/db/instances.go
internal/server/db/networks.go
internal/server/db/profiles.go
internal/server/db/query/retry.go
internal/server/db/query/transaction.go
internal/server/db/storage_pools.go
internal/server/db/storage_volume_snapshots.go
internal/server/db/storage_volumes.go
internal/server/instance/drivers/driver_common.go

- internal/server/db: Remove function `doDbScan`
- internal/server: Use `Retry` function
- internal/server/db: Unwrap dbQueryRowScan function
- internal/server/db: Unwrap queryScan function
- internal/server/db: Remove exec function

Internal DB changes

---

doc/installing.md

- https://discuss.linuxcontainers.org/t/add-documentation-of-incus-compile-instruction-on-alpinelinux/18391
- I'm not a member of AlpineLinux
- I currently do not have enough knowledge on AlpineLinux packages and the ability to manage packages
This PR adds Incus build instruction on AlpineLinux.
AlpineLinux is lightweight Linux distro suitable for containers and virtualization even as host operating system.
Add build and running instruction of Incus on AlpineLinux, so Incus can be used by wider users.
See the forum reference link above for my personal use-case of AlpineLinux and Incus.
I used `Other distros: [distro name here]` in the commit but I'd like to accept suggestion for better prefix. The final ToC will look like:
```diff
Install Incus from source
From source: Build the latest …
```

doc: Add build instruction on AlpineLinux

---

cmd/incus-agent/metrics.go
internal/server/instance/drivers/driver_qemu_metrics.go
internal/server/metrics/api.go
internal/server/metrics/metrics.go

The internal agent API was using maps rather than slices for a variety of metrics.
The problem with that approach is that if the key of that map happens to be present multiple times, as is the case with filesystem mounts, only the last record would be sent through...

Fix missing VM metrics

---

doc/authentication.md

The command to add a users certificate used to be `incus config trust add <cert>` but this was split into a separate command `incus config trust add-certificate <cert>`, it was just not updated in the authentication documentation mentioning this command; this PR fixes that.

Update outdated reference to new command for adding certificate

---

CONTRIBUTING.md

This PR fixes url to documentation. Current one is invalid.

doc: Fix url to documentation in CONTRIBUTING.md

---

cmd/incusd/certificates.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/db/cluster/certificates.go
internal/server/db/cluster/certificates.mapper.go
internal/server/db/cluster/schema.go
internal/server/db/cluster/update.go
internal/version/api.go
shared/api/certificate.go

Adds description field on certificate entries and possibility to modify description using API.
Closes #246

Add description field on certificate entries

---

.golangci.yml
Makefile
client/incus_instances.go
doc/howto/storage_pools.md
doc/reference/storage_cephfs.md
internal/server/firewall/drivers/drivers_nftables.go
test/lint/golangci.sh

Those are the remaining commits from the LXD repository prior to its re-licensing under the incompatible AGPLv3 license, no further changes will be imported from LXD.

Import LXD changes (last batch before the re-licensing)

---

internal/server/instance/drivers/driver_qemu.go

As those rules are only used for new installations of the agent, it doesn't actually make sense to put the legacy rule in place.

incus/instance/qemu: Remove legacy udev rule

---

cmd/lxd-to-incus/validate.go

lxd-to-incus: Add shiftfs check

---

internal/server/config/generate/incus_doc.go
internal/server/metadata/configuration.json

This was causing WebUI crashes as the assumption was that all description fields would always be strings.

Fix incorrect type in JSON metadata

---

doc/installing.md

I intend to port over the current `LXD` wiki page at some point, but left it out until it exists.

doc/installing: Add Arch instructions

---

cmd/lxd-to-incus/main.go

Creating this touch file allows us to add a ConditionPathExists to the lxd service to make sure it won't start on a host that was migrated. NixOS users will have to reconfigure their host after migration to remove LXD, so there will likely be a non-zero period where both services are installed and enabled.

lxd-to-incus: touch completion file after migration

---

cmd/incusd/api_cluster.go

Without that, the updated global config (or server name) doesn't make it into the state which is passed on through other functions.

incusd: Refresh the state on cluster put/join

---

cmd/incus/completion.go
cmd/incus/config.go
cmd/incus/network.go

The shell handles the filtering for you, but we could try and filter by remote name for example in class someone hits tab again.
~I'll probably finish building out network to see if I can just reuse this function or the bulk of it, but this is a start.~ Done.
Example
``` fish
─❯ incus network show <TAB>
bond0    fast1           incus1:fast0  incus1:oob0      oob0
bridge0  incus1:bond0    incus1:fast1  incus1:vlan2010  vlan2010
fast0    incus1:bridge0  incus1:lo     lo
```
One can also explore these directly
```
─❯ go run ./cmd/incus __complete network show ""
incus1:lo
incus1:oob0
incus1:bond0
incus1:bridge0
incus1:vlan2010
incus1:fast0
incus1:fast1
lo
oob0
bond0
bridge0
vlan2010
fast0
fast1
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

incus/network: add dynamic command line completions

---

cmd/incusd/api_cluster.go

The database functions return maps which are inherently unsorted, this then would turn the MemberConfig slice under a similarly unsorted slice..
That's a problem because our own CLI and some 3rd party tools will ask the user to answer each of the MemberConfig questions during join.
The user may assume that when joining multiple systems, the questions will be in the same order on all systems, when they're not, they may incorrectly answer some of the questions.

incusd/cluster: Ensure the cluster member config is always sorted

---

internal/server/network/acl/acl_load.go
internal/server/network/acl/acl_ovn.go
internal/server/network/acl/driver_common.go

With the recent changes to use ClusterTx everywhere, we now had a situation where we'd attempt to create a new transaction from usageFunc while it was called from within another transaction.
This would fail, hit the timeout and cause a transaction retry, which would similarly still timeout, eventually causing the operation to fail.

incusd/network/acl: Avoid nested DB transactions

---

internal/server/instance/drivers/driver_qemu.go

This adds support for directly using seabios as the CSM firmware rather than using EDK2's chain boot feature. It also makes this behavior be the preferred one for new CSM-enabled VMs.
The reason for this change is the removal of CSM support from recent EDK2.

incusd/instance/qemu: Start using seabios as CSM firmware

---

cmd/incusd/main_forknet.go

incusd/forknet: Handle wifi detach

---

cmd/incusd/api_cluster.go
cmd/incusd/daemon.go
cmd/incusd/events.go

So to describe what's going on here. We've recently seen a number of failures, primarily hitting the clustering image refresh tests.
Digging into those failures, it looked like the image propagation was just left hanging indefinitely, eventually hitting a 120s timeout in the test and failing due to images apparently having refreshed correctly across project but the old image was left around.
The high level of image refreshes is:
- Incus is told to refresh the images (by the test or through a timer during normal operation)
- It fetches the new image and figures out what projects need updating
- It detects that the image is present on multiple servers in the cluster
- It sends out copies of the image to those other servers
- Once all servers got the new image, the old image is deleted
Based …

Fix rare race condition in event handling

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
doc/api-extensions.md
doc/config_options.txt
grafana/incus.json
internal/server/cluster/config/config.go
internal/server/loki/loki.go
internal/server/metadata/configuration.json
internal/version/api.go

Add support for `loki.instance`

---

cmd/incusd/api_cluster.go

This joins two consecutive cluster transactions and fixes the missing
error check in the first transaction.

cmd/incusd/api_cluster: Join cluster transactions

---

doc/.wordlist.txt
doc/installing.md

Incus has now a [winget package](https://github.com/microsoft/winget-pkgs/pull/131752) available and the Windows installation docs have been updated with the instructions to install Incus with winget.
ps: I tried using stacked tabs, but the result was not good, so that's why the instructions are stacked.
ps2: while running the `make doc` from Ubuntu on WSL (what else?), I came across a package missing: `python3.10-venv`. Nothing critical, more a FYI.
Signed-off-by: Nuno do Carmo [nuno.carmo@suse.com](mailto:nuno.carmo@suse.com)

Docs windows install update

---

cmd/incus/file.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
test/suites/filemanip.sh

This adds a new `incus file create` subcommand which allows creating files,
symlinks, and directories without having to specify a source.

Add `incus file create` subcommand

---

doc/metrics.md

The `scrape_interval` is assumed to be 15s by the Grafana Prometheus data source by default.the Grafana `$__rate_interval` value will be calculated incorrectly and possibly cause a `no data` response in queries using it.

Add note about scrape_interval and update examples

---

cmd/incus/file.go

This removes the leftover `flagContent` variable in `incus file create`.

cmd/incus: Remove unused `flagContent` variable in `incus file create`

---

doc/environment.md
doc/packaging.md
internal/server/apparmor/instance.go
internal/server/apparmor/instance_qemu.go
internal/server/instance/drivers/agent-loader/incus-agent
internal/server/instance/drivers/agent-loader/incus-agent-setup
internal/server/instance/drivers/agent-loader/install.sh
internal/server/instance/drivers/agent-loader/systemd/incus-agent.rules
internal/server/instance/drivers/agent-loader/systemd/incus-agent.service
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_config_test.go
internal/server/instance/drivers/driver_qemu_templates.go

This adds support for a separate 9p/virtiofs share for the agent which will be shared system-wide (saves us from data duplication) and can contain multiple binaries to handle multiple architectures and operating systems.
Closes #263

Add support for multiple agent binaries

---

cmd/incusd/api_cluster.go
cmd/incusd/daemon_images.go
cmd/incusd/daemon_storage.go
cmd/incusd/images.go
cmd/incusd/storage_volumes.go
cmd/incusd/storage_volumes_snapshot.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/network/acl/acl_load.go
internal/server/network/acl/acl_ovn.go
internal/server/network/driver_ovn.go
internal/server/network/zone/record.go
internal/server/network/zone/zone.go

This attempts to merge consecutive ClusterTx transactions.

Optimize db transactions

---

cmd/incusd/api_internal.go

This code block is unreachable because if `dbVolume` is not nil, an
error is returned a few lines above.

api_internal: Remove unreachable code

---

doc/installing.md

Slowly adding more (gentoo-related) wiki content.

doc/installing.md: add a gentoo-wiki link under Gentoo section

---

doc/api-extensions.md
doc/reference/devices_disk.md
internal/server/device/disk.go
internal/server/instance/drivers/agent-loader/incus-agent-setup
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/project/permissions.go
internal/version/api.go

With this, a new `agent:config` disk source can be used to attach a custom ISO to a VM.
This ISO then contains roughly the same data as the normal `9p` config drive.
The goal behind this is to provide a way for VMs that don't support 9p but do support virtio-serial and virtio-vsock to still run a functional incus-agent.

Add support for an agent drive (ISO)

---

internal/server/instance/drivers/qmp/monitor.go

This would lead to occasional QMP dead locks when the instance would be queried while processing the eject request.

incusd/instance/qemu/qmp: Don't risk blocking QMP on eject

---

internal/server/apparmor/instance_lxc.go

As AppArmor is slowly getting worse and worse at handling mounts due to its design failing to accomodate the new mount APIs, we have to keep relaxing mount rules.
This is another one of those which is required for recent systemd systems.

incusd/apparmor: Allow more mounts in unprivileged containers

---

internal/server/device/disk.go

Fedora variants don't include `mkisofs`, but do include `genisoimage` which is a command compatible substitute. This change checks for `genisoimage` and uses if `mkisofs` isn't found.

fix: use genisoimage when mkisofs is not found

---

test/suites/database.sh

Starting from raft 0.21.0 (which will be released shortly), errors due to lack of disk space will be correctly reported not only in single-node situations, but also in case enough voting nodes run out of disk space so that no further entry can get committed until at least one of them recovers (currently the client would hit a timeout error, with now way for it to know what happened: the command might also eventually succeed far later in the future if disk space is recovered at a later point in time).
Although this is an improvement, it has the slight downside that for single-node situations there will be a short lag before the node actually notices that disk space has recovered and new entries can be committed again. Special-casing the single node situation would be tricky and I'd prefer …

test: Adapt test_database_no_disk_space() to newer libraft versions

---

cmd/incus/completion.go
cmd/incus/create.go
cmd/incus/image.go
cmd/incus/launch.go
cmd/incus/network.go

This covers all the `incus image` subcommands, with the only exception being `incus image get-property myimagename <TAB>` will not complete available properties.

incus/image: add dynamic command line completions

---

doc/.wordlist.txt
doc/authentication.md
doc/remotes.md
shared/cliconfig/remote.go
test/godeps.list

Gives hints and limitations on encrypting the client key.

Improve and document support for encrypted keys

---

cmd/lxd-to-incus/validate.go

lxd-to-incus: Indicate what existing configuration was found

---

client/incus_images.go
client/interfaces.go
client/simplestreams_images.go
cmd/incus/image.go
cmd/incusd/images.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/db/images.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/image.go

```
incus image list --all-projects
+------------------------+-------+--------------+--------+--------------------------------------+--------------+-----------+-----------+-----------------------------+
|        PROJECT         | ALIAS | FINGERPRINT  | PUBLIC |             DESCRIPTION              | ARCHITECTURE |   TYPE    |   SIZE    |         UPLOAD DATE         |
+------------------------+-------+--------------+--------+--------------------------------------+--------------+-----------+-----------+-----------------------------+
| default                |       | 4183ea2d1572 | no     | Ubuntu jammy amd64 (20240202_07:42)  | x86_64       | CONTAINER | 119.16MiB | Feb 2, 2024 at 3:40pm (UTC) |
+------------------------+-------+--------------+--------+-------------------------------------- …
```

Add support for all-projects to incus image list and API

---

internal/server/device/config/consts.go

This avoids an issue on XFS where the base filesystem size is now 300MiB.
Closes #498

incusd/device: Bump base VM filesystem volume to 500MiB

---

cmd/incus-agent/network.go

On some distros, virtio_net may not be loaded by the time the agent starts up.
This isn't really a problem normally as the agent doesn't need access to the network, but it is a problem if the user is using agent.nic_config to rename network interfaces.
So just attempt to load virtio_net prior to performing any reconfiguration.

incus-agent: Load virtio_net before configuring NICs

---

internal/server/storage/backend.go
internal/server/storage/quota/projectquota.go

Improvements to empty instance handling

---

cmd/incusd/instances_post.go

incusd/instances: Use correct project on cross-project copy

---

cmd/incusd/instances_post.go

incusd/instances: Don't bypass instance limit check

---

cmd/incusd/api_internal.go
cmd/incusd/api_internal_recover.go
cmd/incusd/instance.go
cmd/incusd/instance_test.go
cmd/incusd/instances_post.go
cmd/incusd/snapshot_common_test.go
internal/server/instance/drivers/driver_common.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_utils.go

1. Disable the architecture check when performing `incus cp`/`incus mv`.
2. Check architecture when trying to run instance.
Fixes: #478

Disable the architecture check on `incus copy`/`incus mv`

---

cmd/incus/admin_init_interactive.go
cmd/lxd-to-incus/validate.go
doc/api-extensions.md
doc/explanation/storage.md
doc/howto/disaster_recovery.md
doc/howto/storage_volumes.md
doc/reference/storage_lvm.md
doc/rest-api.yaml
internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go
internal/server/storage/drivers/load.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/storage_pool.go

Introduce clustered LVM (shared block storage)

---

internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go

When using a clustered LVM setup and performing live migrations, the logical volumes must be mappable on both the source and target concurently.
This is usually a bad idea and having a volume in that mode also prevents a number of other LVM operations like making snapshots.
So rather than keeping all our VM related volumes in shared mode, let's instead only flip them into sharable mode as part of a migration and flip them back to exclusive mode as soon as possible.

incusd/storage/lvm: Tweak locking in cluster

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/storage/drivers/driver_lvm_volumes.go
shared/subprocess/proc.go

QEMU doesn't like dealing with more than 240 hotplug CPU slots and some OS struggle with more than 64, so put a cap to the max exposed CPUs to 64 unless the user has purposefully exposed more.

incusd/instance/qemu: Cap hotplug CPU slots to 64

---

internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go

Fixes issue with copying instances which have snapshots across machines with different architecture.

Disable architecture check on `incus cp` with snapshots

---

cmd/incus/completion.go
cmd/incus/project.go
cmd/incus/remote.go

I couldn't find an available list of project config keys to replace the ones from the legacy bash completions. I suspect those were manually entered into that file? This missing available list of all config keys only affects `project set` as the retrieval of keys can use the existing project's config.
These project configs appear to be only codified here, unless I'm missing something https://github.com/lxc/incus/blob/d4d6c93283f0d266d283f949c0c9dd03a297d62a/cmd/incusd/api_project.go#L1066

incus: add completions for remotes and projects

---

cmd/incusd/certificates.go

Hi,
I have an Incus cluster which is reachable through a VIP managed by Keepalived. The `core.https_address` of each node is set to listen on the VIP (net.ipv4.ip_nonlocal_bind=1 on each node). To add a remote client I followed this procedure:
1. From one of the node (**not the one with the VIP**), I created a token using `incus config trust add <client_name>`
2. On the client I created a new remote using `incus remote add <remote_name> <token>`
But unfortunately it failed with a cryptic error message `Error: Failed to create certificate: Bad certificate add operation data`. If I create the token on the node with the VIP, everything is OK.
Digging through the code I discovered that the problem is due to the token operation retrieval. The code assume that the token operation is a local …

incusd/certificates: Improve token handling when clustered

---

internal/server/apparmor/instance_qemu.go

Specifically deny a couple of files that we don't need and were causing some DENIED entries.

incusd/apparmor/qemu: Silence apparmor failures

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
internal/server/device/device_common.go
internal/server/device/device_interface.go
internal/server/device/device_load.go
internal/server/device/nic_ovn.go
internal/server/network/acl/driver_common.go
internal/server/network/driver_common.go
internal/server/network/driver_ovn.go
internal/server/network/network_interface.go
internal/server/network/network_load.go
internal/server/network/ovn/ovn_icnb.go
internal/server/network/ovn/ovn_icsb.go
internal/server/network/ovn/ovn_nb.go
internal/server/network/ovn/ovn_nb_actions.go
internal/server/network/ovn/ovn_sb.go
internal/server/state/state.go

This ports a number of new functions to libovsdb, merges a couple of functions together and most importantly, moves the OVN clients to the state struct so they can be kept around between requests, significantly reducing resource usage.

Continue porting functions to OVSDB

---

cmd/incus/completion.go
cmd/incus/storage.go
cmd/incus/storage_volume.go

Is it ok to bring in code from `internal/server` ? Or is there another place to get the list of all available storage config options besides https://github.com/lxc/incus/blob/cff35a29ee3d7a2af1f937cbb6cf23776941854b/internal/server/storage/utils.go#L478 This could be used for get/unset for pools/volumes
I also couldn't find a list of available storage drivers, but this is only needed for pool create.

incus: add completions for storage pools and volumes

---

internal/server/auth/driver_tls.go

Allows to use `--all-projects` for restricted users.
Fixes:  #591

Fix `--all-projects` for restricted users

---

internal/server/device/gpu_sriov.go

The NUMA awareness logic re-shuffled some logic which made it so when no NUMA restrictions are in place, no GPU would be found.

incusd/device/gpu_sriov: Fix default handling

---

cmd/incus/completion.go

PR #588 introduced a regression in image names completion, this commit fixes the issue.

incus/completion: fix image names completion

---

cmd/lxd-to-incus/ovn.go

An existing lxdbr0/lxdbr1 bridge is fine and won't be renamed, so those records can be safely skipped.

lxd-to-incus: Handle common existing bridges

---

cmd/incus-simplestreams/main.go
cmd/incus-simplestreams/main_add.go
cmd/incus-simplestreams/main_generate_metadata.go
cmd/incus-simplestreams/main_list.go
cmd/incus-simplestreams/main_remove.go
cmd/incus-simplestreams/main_verify.go
cmd/incus-simplestreams/utils.go
shared/simplestreams/simplestreams.go

This adds a new `incus-simplestreams` command that can be used to generate and manage a basic simplestreams image server.

Introduce `incus-simplestreams`

---

cmd/lxd-to-incus/main.go
cmd/lxd-to-incus/validate.go

This is a bit of a trickier one as LXD 5.21 has added new DB tables and so requires a DB downgrade to the 5.20 schema prior to being able to move the data over to Incus.

lxd-to-incus: Add support for LXD 5.21

---

cmd/incusd/devices.go
doc/api-extensions.md
doc/reference/devices_usb.md
doc/rest-api.yaml
internal/server/device/device_utils_usb_events.go
internal/server/device/usb.go
internal/server/resources/usb.go
internal/version/api.go
shared/api/resource.go

Add serial number option for type usb, and make busnum and devnum available as config keys for device type usb. 

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go

incusd/instance/qemu: Fix handling of > 64 limits.cpu

---

internal/server/device/gpu_sriov.go

For systems with multiple NUMA nodes per socket (NPS), it's always better to select a GPU on the same socket, even if on a different node than going across socket.
This adds a bit of logic to map the current NUMA nodes to the matching set of CPU sockets and then extract all NUMA nodes from those sockets to build a list of fallback NUMA nodes. Those are less optimal than a direct match but still better than potentially going across socket.

incusd/device/gpu_sriov: Implement NUMA fallback (NPS)

---

internal/server/instance/drivers/driver_common.go

This was leading to very odd validation errors in some cases if the instance being considered as part of a cluster restore happened to have a network device that would get an otherwise restricted key be internally set.
The root of the issue was that CanMigrate didn't operate against a copy of the devices but would instead mutate the whole devices config, which would then trigger the validation error when sent through the devices logic for the second time as part of startup.
This issue would only hit if:
- The setup is clustered
- The cluster is evacuated with action=stop
- The user askes for the cluster member to be restored
- The cluster member has one or more instances using a device that internally expands its configuration (like an OVN network card).
- Those instances process such a …

incusd/instance/common: Fix CanMigrate mutating devices

---

internal/server/storage/backend.go

Should the error message "Snapshot count in backup config and storage device are different" occur, I think it is clearer if the actual count values are shown.
(This is one of the errors which can cause `incus admin recover` to fail)

Show the count values in snapshot count mismatch error

---

doc/api-extensions.md
doc/image-handling.md
internal/server/instance/drivers/driver_lxc.go
internal/version/api.go

- **internal/server/instance/lxd: add support for image.requirments.nesting**
- **api: add image_restriction_nesting**
- **doc/images: introduce requirements.nesting**

introduce requirements.nesting for images

---

cmd/incusd/api_internal_recover.go

incusd/recover: Handle instances last

---

internal/server/device/disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go
internal/server/storage/drivers/driver_lvm_volumes.go

This adds a bunch of extra tests for instance disks when `migration.stateful` is set to `true`.
With those checks in place, it's now possible to live-migrate an instance with extra disks so long as those disks are also on a remote storage pool (ceph or lvmcluster).

Fix live-migration with extra disks

---

cmd/incusd/daemon.go
internal/server/util/http.go
test/suites/tls2jwt.sh
test/tls2jwt/tls2jwt.go

Includes #693 and adds:
- Simplification of `tls2jwt`
- Re-ordering of arguments in `tls2jwt` to be the usual `crt` and then `key`
- Update tests to match
- Update server-side logic to not be RSA-specific
- Update server-side logic to be closer to our usual code-style, remove a type-cast and add a couple more checks
Closes #693

Improvements to JWT authentication

---

client/incus.go
client/incus_certificates.go
client/incus_cluster.go
client/incus_images.go
client/incus_instances.go
client/incus_projects.go
client/incus_storage_buckets.go
client/incus_storage_volumes.go

So I expected that this would need a bunch of work in the event handler and operation handler, but after doing a bit of poking, it looks like we've actually added all the needed filtering already and one can actually call `/1.0/events?all-projects=true` today and only get the events that they should be getting (no logging, only operation and lifecycle for projects that they have access to).
I've done a bunch of testing both from the CLI and UI and can indeed only see the expected events.
Closes #292

Use /1.0/events when under OpenFGA

---

doc/api-extensions.md
doc/reference/network_bridge.md
internal/server/db/networks.go
internal/server/db/networks_test.go
internal/server/ip/utils.go
internal/server/network/driver_bridge.go
internal/version/api.go
test/suites/clustering.sh

Closes #672 
This includes all the changes from #672 with them split a bit differently, fixes some issues found with `make static-analysis`, adds an API extension and removes some dead code.

Add support for creating interfaces through `bridge.external_interfaces`

---

internal/server/project/permissions.go

There are currently three valid values for `restricted.devices.disk`.
`block` will block everything, `managed` allows only managed volumes and `allow` allows not only managed volumes but also other types like shared host paths.
When under `allow`, `restricted.devices.disk.paths` can be used to limit the host paths that can be passed into the instance.
But that particular restriction should only apply to unmanaged volumes.
Closes #706

incusd/project: Allow managed volumes under "allow"

---

internal/server/network/driver_ovn.go

This case happens when a network was deleted by the cluster leader but some other servers in the cluster are yet to stop the network and remove themselves as chassis in the HA group.
Closes #709

incusd/network/ovn: Handle chassis group having been deleted

---

cmd/incus/info.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

This PR is in reference to #702 . It adds Usb information to cmd output of resources.

Adding USB support to `incus info --resources`

---

client/incus_storage_volumes.go

Currently `incus storage volume export` command supports only `project` flag. This PR adds support for `target` flag as well.
Fixes: #698

Support target flag for storage volume export command

---

cmd/incus/move.go
cmd/incusd/api_cluster.go
cmd/incusd/api_cluster_test.go
cmd/incusd/daemon.go
cmd/incusd/daemon_integration_test.go
cmd/incusd/instance_post.go
internal/server/sys/os.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

This very seriously reworks the server-side instance move logic.
It had been slowly grown over the years meaning that each addition didn't necessarily fit well with the previous ones.
The new logic is basically split into two main stage:
- Request validation (access control, target selection, ...) and non-migration process (simple renames)
- Instance migration
The instance migration part then got a major overhaul too and now will basically do:
- Handle basic instance rename first
- Handle project and storage pool changes
- Handle cluster server re-location
This should basically allow handling requests that can change one or more of:
- Name
- Location
- Project
- Storage pool
As well as supporting the additional properties controlling live migration, whether to retain snapshots and whether …

Rework server-side instance move

---

doc/howto/projects_create.md

doc/projects: Tweak examples

---

cmd/incusd/daemon.go
cmd/incusd/instances.go

I noticed a few cases where an offline network or storage coming back online on an evacuated host would cause instances coming back online.
As all code paths to instancesStart come from locations attempting auto-start on daemon startup, lets just move the evacuation check to the function itself.

incusd/instances: Don't start instances when evacuated

---

cmd/incus/main_aliases.go

```
─❯ incus alias list
+-------+----------------------+
| ALIAS |        TARGET        |
+-------+----------------------+
| shell | exec @ARGS@ -- su -l |
+-------+----------------------+
| st    | storage list         |
+-------+----------------------+
─❯ incus st <TAB>
incus1:  local:
─❯ incus shell <TAB>
incus1:  local:  saving-terrapin
```
closes: #738

incus/aliases: fix completion regression

---

cmd/incus/profile.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/profile: Add support for creating profile from yaml

---

internal/server/instance/drivers/driver_lxc.go

incusd/instance/lxc: Only apply soft cgroup limits on cgroup1

---

internal/server/device/nic_bridged.go
internal/server/device/nic_ovn.go
internal/server/network/driver_ovn.go
internal/server/network/network_utils_sriov.go
internal/server/network/ovs/ovs_actions.go

Port all remaining OVS functions to libovsdb

---

internal/server/instance/drivers/driver_qemu.go

This commit allows to find SecureBoot images on platforms like Arch

Add missing SecureBoot firmware names

---

client/incus_network_zones.go
client/interfaces.go
cmd/incus/network_zone.go
cmd/incusd/network_zones.go
doc/api-extensions.md
doc/rest-api.yaml
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/network_zone.go
test/suites/network_zone.sh

1. api: network_zones_all_projects
-  Added `network_zones_all_projects` to `internal/version/api.go`
2. incusd/network_zones: Add support for all-projects
- Added support to all-projects by getting all network zones when allProjects field is added to the uri in `networkZonesGet` function.
- Included all-projects to the comments for `networkZonesGet` functon
- Added Project field in the `NetworkZone` struct in `shared/api/network_zone.go`
3. client: Add GetNetworkZonesAllProjects
- Added `GetNetworkZonesAllProjects` that makes a GET request with all-projects field. Added it to `client/interfaces.go`
4. incus/network_zone: Add --all-projects flag to list
- Added flagAllProjects boolean field to cmdNetworkZoneList
- Calls GetNetworkZonesAllProjects when set to true, GetNetworkZones on false …

Add all-projects support for network zones #712

---

cmd/incusd/api_cluster.go
cmd/incusd/daemon.go
internal/server/network/ovn/ovn_nb_actions.go

Stop networks during cluster evacuations

---

internal/server/storage/drivers/generic_vfs.go
internal/server/storage/drivers/utils.go

1. `incusd/storage/drivers: Introduce SparseFileWrapper `
- Added `SparseFileWrapper `struct and `Write `function to `internal/server/storage/drivers/utils.go`
2. `incusd/storage/drivers/vfs: Use SpraseFileWrapper on backup import`
- Changed the `io.Copy` call in `genericVFSBackupUnpack `to use our wrapper struct.
- On Creation
```
ubuntu@ubuntu:~/incus$ sudo du -sch /var/lib/incus/storage-pools/dir/virtual-machines/a1/root.img
254M	/var/lib/incus/storage-pools/dir/virtual-machines/a1/root.img
254M	total
ubuntu@ubuntu:~/incus$ sudo  sha256sum /var/lib/incus/storage-pools/dir/virtual-machines/a1/root.img
3621514d973e5e7f80f7c9302d1348bd2a9789454421ec3f458bac7c0feb9f0c  /var/lib/incus/storage-pools/dir/virtual-machines/a1/root.img
```
- On Import
```
ubuntu@ubuntu:~/incus$ sudo du -sch …
```

Create sparse files on backup import and migration receive

---

cmd/incus/storage.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Add yaml support for storage create

---

cmd/incus/network_acl.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

`incus network acl create` already has support for creation from a yaml configuration file, but the same wasn't printed in the usage information of the command.
This commit updates `incus network acl create` to show example text for `incus network acl create`

incus/network_acl: Add cmd.Example for network acl create

---

cmd/incus/network_forward.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus network forward create` already has support for creation from a yaml configuration file, but the same wasn't printed in the usage information of the command.
This commit updates `incus network forward create` to include an example

incus/network_forward: Add yaml example for create

---

doc/.wordlist.txt
doc/installing.md

As discussed here:
https://github.com/zabbly/incus/issues/41
As I maintain a Dockerfile and docker images for incus, I would like to add that information to make it more accessible to people who don't have better installation options on their distributions.

incus/doc/installing.md: Add Docker information

---

cmd/incus/cluster.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Add customizable columns to incus cluster list

incus/cluster: Add customizable columns to list

---

cmd/incus/network_load_balancer.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus network load-balancer create` already has support for creation from a yaml configuration file, but the same wasn't printed in the usage information of the command.
This commit updates `incus network load-balancer create` to include an example

 incus/network_load_balancer: add Example to create 

---

cmd/incus/network_zone.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

`incus network zone create` already has support for creation from a yaml configuration file, but the same wasn't printed in the usage information of the command.
This commit updates `incus network zone create` to include an example

incus/network_zone: Add example for create command

---

cmd/incus/admin_cluster.go

This is where incusd is installed on Fedora Linux and derivatives, and potentially other distributions that use /usr/libexec for non-path executables.

cmd/incus/admin_cluster: Add libexec path for incusd

---

doc/api-extensions.md
doc/explanation/clustering.md
internal/server/scriptlet/instance_placement.go
internal/server/scriptlet/load/load.go
internal/version/api.go

PR for #652 
We were unable to validate our changes could you please validate for us?

Issue 652: Add instance placement scriptlet extension

---

cmd/incus/storage_bucket.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

`incus storage bucket create` already has support for creation from a yaml
configuration file, but the same wasn't printed in the usage information
of the command.
This commit updates `incus storage bucket create` to include an example.

incus/storage_bucket: Add example for storage bucket create

---

cmd/incus/network_peer.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

`incus network peer create` already has support for creation from a yaml configuration file, but the same wasn't printed in the usage information of the command.
This commit updates `incus network peer create` to include an example.

incus/network_peer: Add example for create command

---

cmd/incus/info.go
cmd/incus/list.go
cmd/incus/list_test.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/instance/drivers/driver_common.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/instance_state.go

Issue #729 
- implemented common.StartedAt
- added StartedAt to InstanceState
- called StartedAt on api calls to ```1.0/instances/{name}/state```

Add instance start timestamp (uptime)

---

client/connection.go

Transient sockets are supposed to be in /run rather than /var, so make it possible to detect that automatically when used.
Closes #800

client/connection: Add support for the socket existing in /run/incus

---

cmd/incus/storage.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Added customizable columns to incus storage list
This solves issue #718 
Signed-off-by: Long Tran<longtran@utexas.edu>

incus/storage: Add customizable columns in list

---

cmd/incus/main.go
cmd/incus/top.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Introduce `incus top`

---

cmd/incus/info.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

commit 879954bb7e4a2b821c5047d1494bd334e6cda289 closes #704 
Signed off by: Joshua Dierker <joshuadierker@gmail.com>
I am still unable to run make static-analysis locally due to shellcheck error.
Also, I get a runtime error locally when I do incus info --resources. It happens on the main branch, at the chassis  info section. It is likely something with my environment but I wanted to bring it to your attention. See image below

Add PCI support to incus info --resources

---

doc/config_options.txt
doc/reference/devices_disk.md
internal/server/device/disk.go
internal/server/metadata/configuration.json

As the title suggests, this simply adds the generated documentation of the disk device is a similar nature to #820 through #824.

Added Generated Documentation for Disk

---

cmd/incus/storage_volume.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/storage_volume: Add yaml support for create

---

cmd/incus/info.go

This pull request introduces changes to the `remoteInfo` function in the `cmd/incus/info.go` file. The changes primarily involve adding nil checks for the `System` struct's `Chassis`, `Motherboard`, and `Firmware` fields before attempting to print their details. This helps prevent potential nil pointer dereference errors and fixes https://github.com/lxc/incus/issues/866.
```
❯ incus info --resources
System:
Type: container
Load:
Processes: 17
Average: 0.04 0.20 0.27
CPU:
Architecture: aarch64
Caches:
- Level 1 (type: Data): 0B
- Level 1 (type: Instruction): 0B
- Level 2 (type: Unified): 0B
Cores:
- Core 0
Frequency: 2000Mhz
Threads:
- 0 (id: 0, online: true, NUMA node: 0)
- Core 1
Frequency: 2000Mhz
Threads:
- 0 (id: 1, online: true, NUMA node: 0)
- Core 2
Frequency: 2000Mhz
Threads:
- 0 …
```

Fix runtime error when chassis, motherboard and firmware are nil

---

internal/server/instance/drivers/agent-loader/install.sh
internal/server/instance/drivers/agent-loader/systemd/incus-agent.service

By default the install script for incus agent attempts to install to `/lib`. This changes it to write to `/etc` instead. Many systems mount `/usr` read-only and `/lib` is usually a symlink to `/usr/lib`. `/etc/` is normally a writable location on all systems.

Change incus-agent install location to writeable location

---

cmd/incus/storage_volume.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

incus/storage_volume/snapshot: Support YAML for creation

---

shared/idmap/shift_linux.go

fd_userns is defiend ad __do_close, so if it is not -EBADF, it will be closed on exit.  So we need to either set it to -EBADF after closing it, or just not manually close it.
My mistake in reviewing the previous patch.

create_detached_idmapped_mount: avoid double close

---

client/incus_projects.go
client/interfaces.go
cmd/incus/project.go
cmd/incusd/api_project.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/db/network_zones.go
internal/server/db/storage_buckets.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Add support for project forced deletion

---

cmd/incus-user/server.go

The description was showing a description like this: `Network for user restricted project user-user-1001`.

Avoid double user-user- in network description

---

cmd/incus/action.go
cmd/incus/console.go
cmd/incus/create.go
cmd/incus/image.go
cmd/incus/launch.go
cmd/incus/rebuild.go
cmd/incus/remote.go
cmd/incus/utils.go
shared/cliconfig/default.go
shared/cliconfig/file.go
shared/cliconfig/remote.go

This updates a bunch of logic to make it less specific to any specific image server protocol.
Basically replacing the bulk of the assumptions that "simplestreams" is the only public image server protocol with instead assuming that when not talking the "incus" protocol, we're likely dealing with an image server.
It also removes a bit of legacy migration logic and ensures that any remote with an empty protocol is properly treated as an Incus server.
Lastly, the `incus console` logic is tweaked to properly handle containers that have stopped quickly before an interactive console can be set up.

Prep work for OCI support

---

doc/howto/cluster_form.md

Clarify the alternative procedure needed when creating a cluster bootstrap server from an existing incus server
From suggestion on forum. Confirmed this is a working procedure: https://discuss.linuxcontainers.org/t/unclear-documentation-issues-when-making-an-in-use-incus-server-into-a-cluster-bootstrap-server/20103

chore: update documentation for forming cluster with existing server

---

doc/api-extensions.md
doc/rest-api.yaml
internal/server/resources/cpu.go
internal/version/api.go
shared/api/resource.go

Part of #486
This implements the first stage of the work to build a profile of CPU flags for servers within a cluster. This stage extends our internal resources API to have access to CPU flags of the servers.

Extend resources API to include CPU flags

---

doc/installing.md

Was following the instructions on Debian 12 (bookworm) and had an issue with the command that had 
`sudo apt install .... liblxc-dev ... `
because on Debian `liblxc-dev` could not be found.  
I switched to an Ubuntu 24.04 and found that `liblxc-dev` is a transitional package for `lxc-dev`.  I.e.
```console
$ apt-cache search liblxc-dev
liblxc-dev - Transitional package - liblxc-dev -> lxc-dev
``` 
Thus changing `liblxc-dev`  to `lxc-dev`  documents a  process that works on both Debian 12 and Ubuntu 24.
Also ran into an issue compiling as Debian 12 installs golang-go version 1.19 which is too old to compile successfully. Added a note for those running Debian stable. 
This PR updates the docs for the above reasons.

Installation documentation update to work on both Debian and Ubuntu

---

doc/api-extensions.md
doc/config_options.txt
internal/server/device/device_utils_disk.go
internal/server/device/disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/metadata/configuration.json
internal/version/api.go

- feat: add support for `io.bus` and `io.cache` for shared filesystems with VMs
- relates to #599

Add support for io.bus and io.cache for shared filesystems with VMs

---

doc/.wordlist.txt
doc/environment.md
doc/installing.md
internal/server/apparmor/instance.go
internal/server/apparmor/instance_qemu.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/edk2/driver_edk2.go

I discovered I wasn't able to run VMs on my RK3588 (ARM64). Although ARM64 [supports UEFI](https://github.com/lxc/incus/blob/main/internal/server/instance/drivers/driver_qemu.go#L1969-L1971) it wasn't able to find appropriate `*.fd` files because it is assumed every architecture was using OVMF. On ARM64 it should be using AAVMF as far as I can tell.
This PR adds support for using AAVMF on ARMv8 architectures and updates the documentation to reflect the code changes.
I've tested creating VMs with these changes on my ARM64 and x86_64 machines but don't have many devices to test against.

Add support for ARMv8 to use AAVMF EFI firmware

---

internal/server/instance/drivers/driver_qemu.go

Rather than checking that we are dealing with bus=auto or bus=9p which are only present if the user specifically requested a given bus through io.bus, check whether the user specifically requested virtiofs-only instead.

incusd/instance/qemu: Fix handling of virtiofs-only disks

---

cmd/incus/storage_volume.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

As someone who was new to incus, I had some confusion about "type" as it related to volumes. This help text update hopefully helps others who are  new to incus not have that same confusion. 
This update does the following: 
* Moved description text from "cmd.Example" section to cmd.Long section.  Now the example sections only have examples. 
* Added additional example to --help for "incus storage volume" command to show virtual-machine example
* added Error text for when the default (custom) is used and reports "not found". Note: this introduces an `if` statement which gives different error messages depending on if someone uses `custom` or not. If that is not ok, feel free to remove. 
* Ran `make i18n` (separate commit)

Improve storage volume help

---

cmd/incus-simplestreams/main_add.go

incus-simplestreams add: can use one or two arguments for unified or split image #888
moved data file code to dataItem type

incus-simplestreams add: can use unified or split image files

---

cmd/incusd/daemon.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/commands.go
internal/server/sys/fs.go

For virtual machines with `migration.stateful=true` and so therefore capable of being live-migrated or just have their runtime state restored on another system, we will now pull the list of CPU flags from all servers of the same architecture across the cluster and generate a CPU definition made from whatever flags they all have in common.
This should result in virtual machines that can be migrated even across different CPU generations.
Closes #486

Compute a cluster-wide baseline CPU definition for VMs

---

internal/server/device/device_utils_network.go

When creating a virtual-machine with ovn, the tap interface inherits the MTU from ovs-system and therefore doesn't have the MTU.
This doesn't happen on container veth interface, the logic for containers are working fine.
I believe it's a bug, and this PR fixed the issue for me.
Let me know if you need any changes.
Thanks for the awesome work in incus.

incusd/device/network: Fix Tap interface MTU when in OVN

---

internal/server/instance/drivers/driver_qemu.go

The "kvm64" CPU definition doesn't exist on aarch64 and possibly on other platforms, so restrict the logic to x86_64 for the time being.

incusd/instance/drivers/qemu: Limit CPU flag calculation to x86_64

---

internal/server/storage/s3/miniod/admin_client.go

The check only passed for the `mc` executable name. This caused the client check to fail on my distribution as the fallback from `mc` to `mcli` didn't pass this condition.

incus/s3: Fix mcli minio client executable name check

---

client/oci_images.go
cmd/incusd/instance.go

This fixes a rather nasty bug in OCI container internal structure creation which would discard some rather critical volatile keys during creation.
On top of that, this also adds additional errors on the client side when tools are missing.

OCI container fixes

---

cmd/incus-simplestreams/main_remove.go

#fixes #994.
also added --verbose flag to print deleted files
Tested by adding and removing combined and split container images.

incus-simplestreams: Handle removal of combined images

---

internal/server/sys/fs.go

This change updates the file mode of `RunDir` to 0711 allowing non-root clients to connect to the unix socket.
Fixes #1003

Change RunDir file mode to 0711

---

internal/server/apparmor/network_dnsmasq.go

Apparently those rules are needed when running Incus nested within an unprivileged container on some platforms.

incusd/apparmor/dnsmasq: Relax rules a bit

---

cmd/incusd/instance_post.go
internal/server/storage/drivers/driver_btrfs.go
internal/server/storage/drivers/driver_ceph.go
internal/server/storage/drivers/driver_cephfs.go
internal/server/storage/drivers/driver_dir.go
internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_zfs.go

As we're dealing with a new internal client, we can't assume that it's got its project set to match that of the instance, as a result we need to set the project even in the case where the instance remains where it is.

incusd/instance_post: Always set the target project

---

Makefile

The option `--exit-on-error' exists only on debian run-parts version. On centos, redhat or federa, run-parts has no such option.
The fix checks version and adds options accordingly.

Make run-parts running compatible with different versions

---

client/incus.go
client/incus_images.go
client/incus_instances.go
client/incus_oidc.go
client/incus_storage_buckets.go
client/incus_storage_volumes.go
cmd/incus/remote_unix.go

This fixes a few remaining issues with OIDC and request retries:
- Some requests weren't going through our wrappers and so were missing a GetBody function
- When using the keepalive proxy, an expiring token would cause a 502 error to be sent back to the client with no indication that a retry is needed and no ability to retry the request due to the proxy not having the original body. We now have logic to detect when a retry is needed, the proxy returns a custom status code back to the client and the client now retries the request if it has what it needs to do it.

Properly handle request retries on OIDC

---

client/incus_images.go
client/incus_instances.go
client/incus_storage_buckets.go
client/incus_storage_volumes.go

The recently added re-send logic works well for anything where we have a fixed buffer we can re-send but would hit issues when using files as source as those would typically be at the end of their content and need to be reset to 0 before reading again.
This PR removes any `GetBody` definition where the content isn't a fixed and where we can't just seek back to the beginning. For those where we can seek, we're now performing the expected Seek call and checking its error so that should the file not actually be seekable (e.g. a pipe), this will fail with the appropriate error.

Fix automatic re-send of unseekable POST queries

---

doc/.wordlist.txt
doc/installing.md

Colima [v0.7.0](https://github.com/abiosoft/colima/releases/tag/v0.7.0) has been released with support for Incus.
This PR adds the instructions for running Incus on macOS with Colima.

doc: add colima instructions

---

doc/.wordlist.txt
doc/howto/cluster_manage.md

doc/clustering: Better document healing

---

cmd/incusd/api.go
internal/server/auth/oidc/oidc.go

This attempts to fix a common issue with HTTP/2 clients which keep a long lasting session with Incus but don't send any traffic over it.
When going through a load-balancer, this will typically lead to the connection getting closed due to timeout. On HTTP/1 this isn't a huge deal as it causes the request to fail and the client can just retry it. But on HTTP/2 such an abrupt disconnection is treated as a full network error and causes all current and subsequent requests to the server to fail, short of reloading the entire page.
On top of that, we had an issue with OIDC authentication expiring after 1 minute and the internal refresh failing to update the cookies in some code paths which would then cause the request to fail with an error. The updated logic will now validate the renewed token …

Fix handling of long running connections

---

internal/server/instance/drivers/driver_lxc.go

This makes the Incus-spawned lxcfs respect the LXCFS_OPTS traditionally found in /etc/default/incus.
Note that because this is pulled from Incus' environment, a change to the file will not immediately affect instances, Incus itself needs to be restarted first.

incusd/instance/lxc: Respect LXCFS_OPTS

---

cmd/incus/create.go
cmd/incus/utils.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

This change adds `--environment-file` to `init/create/launch` commands and reads environment value key pairs from the referenced file, adding them to the config map for the container.

incus: Add support for environment file (.env)

---

doc/api-extensions.md
doc/reference/devices_disk.md
internal/server/device/disk.go
internal/version/api.go
test/suites/container_devices_disk.sh

incusd/device/disk: Allow relative paths within custom volumes

---

cmd/incusd/networks.go
doc/api-extensions.md
doc/reference/network_ovn.md
internal/server/device/nic_ovn.go
internal/server/network/driver_ovn.go
internal/version/api.go

- feat: allow creating isolated OVN networks (no uplink)
- close #936 
- OS: Ubuntu 24.04
- Arch: x86_64
```
root@playground:~/incus# incus network create ovn-none --type ovn network=none --debug
Network ovn-none created
root@playground:~/incus# incus network list
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
|    NAME    |   TYPE   | MANAGED |      IPV4       |           IPV6            | DESCRIPTION | USED BY |  STATE  |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| br-int     | bridge   | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+------------------ …
```

Allow creating isolated OVN networks (no uplink)

---

cmd/incus/remote.go
po/de.po
po/es.po
po/fr.po
po/incus.pot
po/it.po
po/ja.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Part of #1027 
I've tested it and it worked as expected, I even tried adding a new remote server, but not sure though if the way of retrieving the name of the remote server is correct/efficient.

incus/remote/list: Add column flag 

---

client/doc.go

Follows https://discuss.linuxcontainers.org/t/getting-starting-with-client-api-incus-golang-api/21332
Unsure re: explanation on using `incus` because my `vim-go` auto converts `"github.com/lxc/incus/client"` into `incus "github.com/lxc/incus/client"` 🤔 Maybe you have a wording here that will clarify? Can update the PR...

client: docs improvements

---

internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go

This changes the locking behavior around backup files from locking an entire operation to only locking around the writing of the backup itself.
I couldn't figure out the exact reason for locking the entire operation, but this has been confirmed to caused some pretty serious issues with automated backups as any failure to update the backup file would then cause an attempt to delete the new backup, this would call Delete() which is another operation that requires the lock.
This effectively ends up completely deadlocking all backup-related operations on the instance (Start, Delete, Snapshot, ...) with no good way around it under the current locking scheme.

incusd/instance: Fix backup file locking issue

---

doc/howto/incus_alias.md

Fixed typos, simplified language, added notes.

doc: Update incus_alias.md

---

doc/api-extensions.md
doc/config_options.txt
doc/howto/network_load_balancers.md
internal/server/metadata/configuration.json
internal/server/network/driver_common.go
internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go
internal/version/api.go

Add OVN load-balancer health checks

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
doc/api-extensions.md
doc/config_options.txt
internal/server/auth/oidc/oidc.go
internal/server/cluster/config/config.go
internal/server/metadata/configuration.json
internal/version/api.go

This adds the option to customize the effective scope of authorizations via OpenID Connect 1.0.

incusd: allow custom oidc scope

---

internal/server/storage/drivers/driver_lvm_volumes.go

We want the activation state of the LV to be identical following a resize operation, otherwise we may end up having the caller assume it's still active and end up writing data to a file in /dev rather than to an actual device.
This was caught in our daily tests but took a little while to track down.

incusd/storage/lvm: Fix resize logic to conserve LV state

---

cmd/incusd/main_forknet.go

This way if we do get DNS configuration but don't have a suitable default gateway or hit a conflict with another network interface, the DNS configuration will still be saved.

incusd/main_forknet: Tweak DHCP client to apply DNS first

---

doc/cloud-init.md

The config shown in the documentation is not valid. I updated it to use the `users` key since that is what is shown on the linked cloud-init example.
Here is how I tested the new example:
```
[root@server ~]# cat users.txt
#cloud-config
user:
- name: documentation_example
[root@server ~]# cloud-init schema --config-file users.txt
Invalid UNKNOWN_CONFIG_HEADER users.txt
Error: Cloud config schema errors: user: [{'name': 'documentation_example'}] is not of type 'string', user: [{'name': 'documentation_example'}] is valid under each of {'required': ['snapuser']}, {'required': ['name']}
Error: Invalid schema: UNKNOWN_CONFIG_HEADER
[root@server ~]# sed -i 's/user:/users:/' users.txt
[root@server ~]# cloud-init schema --config-file users.txt
Valid schema users.txt
```

doc: Update Cloud-Init User Example

---

internal/server/device/device_utils_network.go

incusd/device/nic: Make burst rate dynamic for ingress traffic

---

doc/api-extensions.md
doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_metrics.go
internal/server/instance/drivers/qemudefault/default.go
internal/server/metadata/configuration.json
internal/server/project/permissions.go
internal/server/scriptlet/instance_placement.go
internal/server/scriptlet/load/load.go
internal/server/scriptlet/logger.go
internal/server/scriptlet/qemu.go
internal/server/scriptlet/starlark.go
internal/version/api.go

This PR adds the ability to call scriptlets at various stages of a VM initialization.
Several modifications to the codebase are proposed:
* A `qemudefault` subpackage has been created to avoid a dependency cycle when allowing the QEMU driver to call scriptlets;
* The scriptlet logger has been moved to a dedicated file, to be reused by other scriptlets;
* The scriptlet creation functions have been transformed to helper functions, to make writing new scriptlets easy;
* A Starlark value unmarshaller has been written
* And finally, the startup scriptlet has been written
For now, the scriptlet only allows running QMP queries, but feel free to add anything you want there!

Add startup scriptlets

---

cmd/incusd/api_internal.go
internal/server/cluster/connect.go
internal/server/instance/drivers/driver_qemu.go
internal/server/storage/backend.go

This fixes two issues:
- Long device names (e.g. UUID) were causing QEMU errors due to the length exceeding the maximum
- Resizing an external (non root) disk would not notify the VM

Storage related fixes

---

internal/server/storage/drivers/driver_ceph_utils.go
internal/server/storage/drivers/driver_ceph_utils_test.go
internal/server/storage/drivers/driver_ceph_volumes.go
internal/server/storage/drivers/volume.go

The regexp logic was very hard to follow and also wasn't properly handling volume names that make use of special characters.
The new logic may be slower but is a lot easier to follow and reason about as well as being a lot easier to tweak in the future to handle more edge cases.
Also reworks the test to output something that's easier to check.

incusd/storage/drivers/ceph: Rework parseParent

---

internal/server/instance/drivers/agent-loader/install.sh

This reverts commit 8dafa2a41772b22dd1bbb14bd51785eb5fac10ad.
On most Red Hat systems, you need to use /var/run/XYZ as there is an equivalency rule in SELinux that points /run to it.
Attempting to directly put a rule on /run/XYZ fails with an error.

Revert "incusd/instance/agent-loader: Don't hardcode path"

---

internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_lvm_utils.go

Querying this value can get extremely expensive on busy systems.

incusd/storage/drivers/lvm: Cache VG extent size

---

internal/server/network/ovn/ovn_nb_actions.go

Despite the documentation mentioning that it can be done per-protocol, it apparently can only be done that way when the MAC isn't known.
Thankfully Incus will always compute an EUI64 address in the IPv6 case, so there should not be an actual need for partial dynamic allocation.
Sponsored-by: Luizalabs (https://luizalabs.com)

incusd/network/ovn: LSP dynamic allocation can't be done per protocol

---

internal/server/instance/drivers/driver_qemu.go

The NVRAM symlink was previously deleted thanks to a bug in the firmware lookup logic. That logic got recently corrected which in turn caused the symlink to no longer be deleted, causing it to occasionaly point to the incorrect target...

incusd/instance/qemu: Always re-generate the nvram symlink

---

internal/server/instance/drivers/driver_qemu.go

This is required in most cases with QEMU 9.1.0.

incusd/instance/qemu: Set O_DIRECT when passing in FDs

---

cmd/incusd/daemon.go
internal/server/apparmor/apparmor.go

This will silence some DENIED caused by incus subcommands triggering the apparmor version detection logic.

incusd/apparmor: Only initialize with the daemon

---

doc/config_options.txt

The documentation for `limits.memory` currently states `1Gib`, but this doesn't seem to be a valid unit.
https://linuxcontainers.org/incus/docs/main/reference/instance_units/
Today, I tried to configure settings based on this documentation, but I encountered an error stating that the unit was invalid, which made me realize the unit was misspelled.
Using my IDE's search function, I quickly searched for `Gib`, `Mib`, and `Tib`, but found no other occurrences.

doc: Fix limits.memory default value unit

---

internal/server/instance/drivers/driver_qemu.go

Windows guests don't support virtiofs-9p or virtio-vsock devices, so don't include them in the generated qemu config.
Depends on the instance's configuration field `image.os` containing the string "Windows" somewhere in its value.

internal/server/instance/drivers: Disable 9p and vsock for Windows VMs

---

cmd/incus/action.go
cmd/incus/launch.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

This PR fixes a problem where, in case of an error, the CLI would prompt the user to run an invalid command if they had specified a project other than the default one.
Before:
```
#> incus start debian --project test
Error: Failed to run: <...>
Try `incus info --show-log debian` for more info
```
After:
```
#> incus start debian --project test
Error: Failed to run: <...>
Try `incus info --show-log debian --project test` for more info
```

Properly handle `--project` in CLI error messages

---

cmd/incusd/instance_console.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_config_test.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/instance_interface.go
internal/server/instance/operationlock/operationlock.go

This adds the capability for VMs to fetch console history in a similar manner to containers (`incus console --show-log <instance>`).
The console backend device is changed to be a ring buffer by default, which we can query for history since the VM started up. When an interactive console is needed (ie, running `incus console <instance>`) the ring buffer is swapped out for a socket, and when done is replaced again by the ring buffer.

Allow VMs to pull console history similar to containers

---

internal/server/instance/drivers/driver_qemu.go

Right at VM creation, the ring buffer for the console is empty. If you try to access an interactive console, such as by running a command like `incus launch images:ubuntu/24.04 v1 --vm --console`, you'd get an error that the log file doesn't exist when attempting to save off the ring buffer contents prior to switching to the unix socket connection. We shouldn't return an error, but rather an empty string in this case.

Don't return an error if console log file doesn't exist

---

internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go

This PR fixes issue that `dns.search` network configuration was not honored when IPv6 was disabled.

Allow to use `dns.search` when only IPv4 is enabled

---

doc/installing.md

Using Nvidia GPU when building from source in OpenSUSE requires some extra notes that are missing.
1. LXC hooks (which includes Nvidia hooks) are missing in OpenSUSE unless `lxc` package is installed
2. Nvidia container tools is required but not mentioned anywhere (this could be moved/added in another section in the future).

doc: add note for Nvidia usage when building from source in OpenSUSE

---

cmd/incus-agent/state.go
cmd/incus/info.go
doc/api-extensions.md
doc/rest-api.yaml
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/instance_state.go

This adds operating system details to an instance's state. `incus-agent` has been extended to populate this information when running within a VM.
```
$ incus info debian
Name: debian
Status: RUNNING
Type: virtual-machine
Architecture: x86_64
PID: 658181
Created: 2024/09/13 16:13 MDT
Last Used: 2024/09/20 11:59 MDT
Started: 2024/09/20 11:59 MDT
Operating System:
OS: Debian GNU/Linux
OS Version: 12 (bookworm)
Kernel Version: 6.1.0-25-amd64
Hostname: debian
FQDN: debian.testing.local
Resources:
Processes: 16
[snip]
```

Add operating system details to instance state

---

cmd/incus-migrate/transfer.go

If we convert a VM disk image when importing it, we shouldn't then copy that temporary image to the final storage location.

cmd/incus-migrate: Don't copy converted VM image

---

doc/contributing.md

Missing prerequisites may hinder documentation contributions as it may throw errors when running `make doc` (specially the Python version) or when trying to validate spellcheck or linting.
Personally I found I had those tools missing when trying to compile the doc first time and Sphinx uses a python notation that is available since 3.8 but the error thrown is cryptic if python version is older.

doc: add prerequisites section for building documentation

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/qmp/errors.go

* Don't return an error if VM's console device isn't a ringbuf
* Don't conflict with live migration operation

VM console log fixes

---

internal/server/instance/drivers/driver_qemu.go

Some users, primarily those who migrated from LXD have a qemu.nvram which isn't a symlink, making it impossible to know what firmware to match it with.
To fix this, detect such environments and re-generate the NVRAM.
Closes #1202

incusd/instance/qemu: Fix issues with old NVRAM

---

internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/util.go

fix https://github.com/lxc/incus/issues/1261
Just extract the logic of driver_lxc.go for the memory percentage value into a function and apply it to driver_qemu.go

Allows the VM's limits.memory configuration to be set to a percentage value

---

internal/server/instance/drivers/driver_lxc.go

For OCI containers, mount /run if the path exists in the container and it's not been mounted already.
Not all OCI images define /run as a mountpoint despite often expecting it to be a tmpfs.

incusd/instance/lxc: Mount /run if the path exists

---

cmd/incusd/api_cluster.go
cmd/incusd/api_cluster_evacuation.go

Sequentially evacuating or restoring a server can be slow when there are several instances running. This switches to running migrations in parallel, based on the number of detected CPUs available.

Run cluster evacuate and restore in parallel

---

doc/.wordlist.txt
doc/installing.md

The alpine community repository `(http://dl-cdn.alpinelinux.org/alpine/v3.15/community)` does not contain the `incus` packages. It's only available in `http://dl-cdn.alpinelinux.org/alpine/edge/community` mirror (which is not enabled by default).

docs: mention alpine edge repository in alpine installation

---

cmd/incus/file.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

This is the modification of ```incus file delete``` as a start. Please let me know if the implementation is acceptable and I'll proceed with the other operations.
Note: I noticed that it throws an error if trying to delete a directory that includes contents, thus, I've added ```--force``` flag in case the user still wants to delete a directory with all its contents. Please let me know if that is not required I can remove it.

Change incus file delete operation to sftp

---

doc/api-extensions.md
doc/reference/network_ovn.md
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go
internal/server/network/network_utils.go
internal/version/api.go

- Allow adding external interfaces to an OVN network
- close #937
- OS: Ubuntu 24.04
- Arch: x86_64
**create OVN network with `bridge.external_interfaces`**
```
Network ext-ifac-ovn created
+--------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
|     NAME     |   TYPE   | MANAGED |      IPV4       |           IPV6            | DESCRIPTION | USED BY |  STATE  |
+--------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| br-int       | bridge   | NO      |                 |                           |             | 0       |         |
+--------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| ens18        | …
```

Allow adding external interfaces to an OVN network

---

internal/server/instance/drivers/driver_qemu.go

The previous submission  https://github.com/lxc/incus/pull/1270 only applied to newly created or shut down virtual machines. This submission fixes the `limits.memory` update for running virtual machines.

fix live update VM's limits.memory configuration when use a percentage value

---

internal/server/instance/drivers/driver_lxc.go

Apparently some containers put executables in /run...

incusd/instance/lxc: Remove restrictions on /run

---

internal/server/instance/drivers/edk2/driver_edk2.go

Incus is packaged for Chimera Linux; this addition provides support for edk2 filenames as packaged by Chimera Linux (these are the base filenames supplied by the qemu/edk2 package https://github.com/qemu/edk2).
Have built and tested on x86_64 arch / Chimera Linux (musl libc); both containers and virtual machines (security.secureboot=false) perform as expected.

incusd/internal/server/instance/drivers:  support for Chimera Linux (qemu/edk2) pkg layout

---

internal/server/device/nic_bridged.go

A NIC configuration being considered invalid, such as an IPv4 or IPv6 address now being outside of the scope of the parent network shouldn't impact the proper removal of that device or the deletion of the instance it belongs to.
Because the config["network"] to config["parent"] step typically only happens late in the loading process (post validation), the postStop and remove actions may be called without that config key having been expanded. Rather than fail and leave leftovers behind, lets detect that case and determine the correct bridge name.
Closes #1265

incusd/device/nic/bridged: Handle invalid configuration

---

doc/installing.md

docs/installing.md in support of Chimera Linux.

doc/installing: Update for Chimera Linux

---

shared/cgo/process_utils.h

shared/cgo: Don't use strlcpy

---

client/incus_oidc.go
client/util.go
cmd/incus/main.go
cmd/incus/remote_unix.go
cmd/incus/top.go
cmd/incus/webui.go
cmd/incus/webui_unix.go
cmd/incus/webui_windows.go
cmd/incusd/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/util/browser.go

This implements a new `incus webui` command which will:
- Check if the server has the web UI installed
- Spawn a tiny web server for HTTP requests on localhost
- Generate an authentication token to avoid other clients on the machine from accessing Incus
- Open the user's web browser with a URL including that token
The result is that running `incus webui` will open your current web browser to the Incus UI without requiring Incus itself to listen on the network, or have to deal with Incus' TLS authentication and TLS certificate verification.

Implement `incus webui`

---

internal/server/scriptlet/instance_placement.go
test/suites/clustering_instance_placement_scriptlet.sh
test/suites/clustering_move.sh

incusd/scriptlet: Make set_target fail with invalid members

---

doc/reference/instance_options.md
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/scriptlet/load/load.go
internal/server/scriptlet/qemu.go

Export QMP functions

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_metrics.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/scriptlet/qemu.go

internal/server: Log QMP interaction to a file

---

client/incus_oidc.go

This adds a helper method to fetch the OIDC tokens (if any) from the OIDC client used to authenticate to an Incus server. In the vast majority of cases, the tokens are automatically saved/restored from the remote's configuration. However, when operating without a configuration file, such as a standalone tool, there's no way to save the tokens for later use. This results in an authentication prompt every time a new connection is established rather than being able to re-use a previously acquired token.

Add a GetOIDCTokens() method

---

cmd/incus/project.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
test/suites/projects.sh

This pull requests adds a new command to show the current project.
```
$ incus project get-current
default
$ incus project create foo
$ incus project switch foo
$ incus project get-current
foo
```

Add get-current to show current project

---

internal/instance/config.go

The `0` value isn't valid for a `limits.cpu`, but for a NUMA node, it is valid to want to pin to node `0`.

internal/instance: Allow 0 as value to limits.cpu.nodes

---

cmd/incus/monitor.go
cmd/incusd/api_cluster_rebalance.go
cmd/incusd/api_internal.go
cmd/incusd/daemon.go
doc/api-extensions.md
doc/config_options.txt
doc/howto/cluster_manage.md
internal/instance/config.go
internal/server/cluster/config/config.go
internal/server/instance/instance_utils.go
internal/server/metadata/configuration.json
internal/server/scriptlet/instance_placement.go
internal/version/api.go

This PR adds feature to automatically move some workloads to re-balance load across cluster.
The logic works in following way:
- Spawns a background task which is performed on the current leader
- Calculates a per-server score (based on CPU and memory)
- Splits the servers by CPU architecture, then sort the servers by their score and check difference between most and least busy for each architecture, exit the re-balance if the difference is less than the threshold
- Pulls the list of instances from the most busy server and filter out those that cannot be live migrated
- Determines what instances should be migrated to equalize the score between the two servers looking at their current memory usage and CPU allocation and migrate them
Fixes: #485
Closes: #835

Automatic live-migration to balance load on cluster

---

cmd/incus/top.go
cmd/incusd/images.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go

incusd/instances/publish: Fix base metadata

---

internal/server/instance/drivers/driver_qemu.go

This fixes an issue where we'd get both stopped and migrated events during live-migration as the console retrieval happening during the migration would mark the migration operation as completed, turning the final stop operation into its own entity rather than completing the migration operation.

incusd/instance/qemu: Don't take over operations on console retrieval

---

cmd/incusd/instance_exec.go

exec: Consume websocket pings for stderr

---

cmd/incus-simplestreams/main.go
cmd/incus-simplestreams/main_prune.go

This PR adds a prune command to incus-simplestreams which:
- Removes orphaned image tarballs (those not referenced by images.json)
- Finds any broken image and deletes them from the index
- Removes older versions of a product, retaining only the most recent one
Closes #1303

incus-simplestreams: Add prune command

---

shared/cgo/process_utils.h

New clang-14 reports errors for directly casting from an integer to a pointer. Use uintptr_t to fix that problem and adhere to the casting rules.
Fixes: https://github.com/lxc/incus/issues/1395

cgo/process_utils: fix 32bit builds

---

internal/server/instance/drivers/edk2/driver_edk2.go

The Vars file mappings in the edk2 driver were incorrect for the SECUREBOOT usage. The previous mapping for "ovmf-x86_64-ms-4m-vars.bin" and "ovmf-x86_64-ms-4m-code.bin" was swapped. This commit corrects the mapping by ensuring the proper Vars files are associated with their respective Code files. The change solves an issue in distributions using these file names, such as openSUSE.

incus/internal/server/instance/drivers/: Fix incorrect Vars file mapping in edk2 driver

---

internal/server/storage/drivers/driver_zfs.go
test/suites/storage_driver_zfs.sh

If a user has set up their own zpools and given them to us to manage,
it's possible they've configured ZFS-native encryption. For the most
part, this works completely transparently to us. However, because we
manually do zpool-import and zpool-export during startup and shutdown of
Incus, ZFS datasets with keys will have their keys unloaded during
shutdown and then the keys are not automatically loaded on startup. This
results in containers being unable to start on startup because all IOs
are blocked indefinitely until the dataset keys are loaded manually by
the admin -- even if the admin has configured automatic key loading on
their system!
The simplest solution would be to pass -l to zfs-import (which causes
ZFS to auto-import all keys for all datasets in the pool). However, it
is …

zfs: load keys for encrypted datasets during pool import

---

cmd/incusd/instance.go

With the Terraform provider we've managed to delete an image as it was being unpacked, leading to obvious problems, so let's make sure that we hold the image lock when triggering an unpack.

incusd/instance: Lock image access

---

internal/server/storage/drivers/driver_lvm_utils.go

This PR removes metadata information from the space usage calculation for the LVM driver. Consequently, the `total space` and `space used` values reported by the `incus storage info` command will now exclusively represent the data logical volume (LV).
Closes: #1414

Remove metadata info from space usage calculation

---

doc/api-extensions.md
doc/reference/storage_btrfs.md
doc/reference/storage_ceph.md
doc/reference/storage_cephfs.md
doc/reference/storage_dir.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md
internal/server/storage/drivers/volume.go
internal/server/storage/utils.go
internal/version/api.go
test/suites/storage_volume_initial_config.sh

Add ability to set the initial owner of a custom volume

---

cmd/incusd/instance_post.go
cmd/incusd/instance_snapshot.go
cmd/incusd/instances_post.go
cmd/incusd/migrate.go
cmd/incusd/migrate_instance.go
doc/api-extensions.md
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go
internal/server/migration/migration_volumes.go
internal/server/storage/drivers/driver_ceph_volumes.go
internal/server/storage/drivers/driver_lvm_volumes.go
internal/version/api.go

This PR introduces the ability to move virtual machines between storage pools while they are running. For example, executing:
`incus mv vm1 --target server01 --storage new-pool`
enables a live migration of the VM to a different storage pool. The `--storage` flag must be used in conjunction with the `--target` flag. This approach treats the operation as a traditional live migration, avoiding scenarios where both the source and target reside on the same machine.
Closes #1064

Allow local live-migration between storage pools

---

client/simplestreams_images.go
shared/simplestreams/simplestreams.go
shared/util/net.go

if download by hash fails with 404 not found.
Fixes #1373

client: invalidate simple streams cache

---

cmd/incusd/instances_post.go

The StoragePool field should only be set if a full cross-pool migration is expected to occur. This isn't normally the case within a cluster when the pool name itself doesn't change.

incusd/instances_post: Fix cluster internal migrations

---

cmd/incusd/main_forknet.go
internal/server/instance/drivers/driver_lxc.go

Fix DHCP client keeping container up

---

cmd/incusd/instance_console.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/instance_interface.go
internal/server/response/response.go
internal/version/api.go

Add support for VGA console screenshots

---

cmd/incus/image.go
cmd/incus/publish.go
cmd/incus/utils.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
test/main.sh
test/suites/image.sh

Add --reuse to incus image import

---

cmd/incusd/migrate_storage_volumes.go
internal/server/storage/backend.go
test/suites/storage_local_volume_handling.sh

This PR fixes an issue when copying a custom volume between two different hosts using the `--refresh` flag.
A creation date was added to the necessary struct, and this information is now properly populated.
The `UnixNano` function is used because the database stores time information with nanosecond precision.
After this fix, some tests were failing because the snapshots on vol6 had different creation dates, so all snapshots were replaced. Currently, in the first stage, we copy snapshots (with the `--refresh` flag) between two different pools. In the second stage, we create two new snapshots: one in the source pool and one in the target pool. After that, the copy operation with the `--refresh` flag is performed again. The result is as follows:
- Existing snapshots remain unchanged.
- The …

Fixes an issue when copying a custom volume using the `--refresh` flag

---

internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go

incusd/storage/lvm: Require 512-bytes physical block size for VM images

---

cmd/incusd/migrate_storage_volumes.go

The `LastUsedDate` field is not utilized by volume snapshots and can be removed to avoid confusion.
The `ExpiryDate` field is currently unused but can be populated to provide clarity.

incusd: Fill ExpiryDate and remove LastUsedDate in volumeSnapshotToProtobuf

---

cmd/incus/cluster.go
cmd/incus/cluster_group.go
cmd/incus/completion.go
cmd/incus/copy.go
cmd/incus/file.go
cmd/incus/image.go
cmd/incus/list.go
cmd/incus/move.go
cmd/incus/network.go
cmd/incus/network_acl.go
cmd/incus/network_zone.go
cmd/incus/profile.go
cmd/incus/project.go
cmd/incus/publish.go
cmd/incus/storage.go

Completion for files inside instances is not provided as I don't know how to do it properly for the moment, the improvement concerns the fact that instances names are now returned as completion candidates. Before only local file names was provided.

incus: Improve completion for `file push` and `file pull`

---

doc/installing.md

Native packages are now available, so no more need for the COPR repository.
Closes #1455

doc/installing: Update Fedora instructions

---

cmd/incusd/certificates.go
cmd/incusd/daemon.go
internal/server/cluster/gateway.go
internal/server/cluster/gateway_test.go
internal/server/cluster/heartbeat_test.go
internal/server/cluster/membership_test.go
internal/server/cluster/upgrade_test.go
test/suites/pki.sh

This resolves the issue reported as LXD CVE-2024-6156

Fix gap in validation of pre-existing certificates when switching to PKI mode

---

doc/howto/network_forwards.md

doc/network_forwards: Split configuration into own table

---

cmd/incus/completion.go
cmd/incus/image_alias.go

When there was no remote part in the alias, remote names was included in the fingerprint completions which was wrong.

incus: Fix completion for `image alias create`

---

cmd/incus/main.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po

Sometimes the error message displayed when the execution of an alias
fails can be a little bit hard to decipher. So to better understand
the error, when an error occurs due to the execution of an alias, its
expansion is displayed along with the error message.

incus: Display the alias expansion when execution of an alias fails

---

cmd/incus/main.go
cmd/incus/main_aliases.go
cmd/incus/main_test.go

- Remove the limitations stated in 50373fef4298d343ef64d8375c2706347f77b7de
- Fix completion handling

incus: Fix alias arguments handling

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
doc/api-extensions.md
doc/authorization.md
doc/config_options.txt
internal/server/auth/authorization.go
internal/server/auth/common/common.go
internal/server/auth/driver_common.go
internal/server/auth/driver_openfga.go
internal/server/auth/driver_scriptlet.go
internal/server/auth/driver_tls.go
internal/server/cluster/config/config.go
internal/server/metadata/configuration.json
internal/server/scriptlet/auth/auth.go
internal/server/scriptlet/instance_placement.go
internal/server/scriptlet/load/load.go
internal/server/scriptlet/log/logger.go
internal/server/scriptlet/marshal/marshal.go
internal/server/scriptlet/marshal/marshal_test.go
internal/server/scriptlet/qemu.go
internal/version/api.go
test/suites/authorization_scriptlet.sh

Add authorization scriptlet

---

client/oci_images.go
cmd/incusd/daemon_images.go

I ran into some challenges while trying to get the new incus OCI image support working with a Google Cloud registry (Artifact Registry).  The good news it was all self inflicted and the feature worked as designed, but it wasn't easy to debug given the reliance on skopeo/umoci and lack of logging and error pass throughs.  
Added debug logging of the skopeo and umoci std err.  This is especially useful with authenticated connections that need to use the auth.json configuration file to work.
I considered changing the error handling / pass through logic in `ImageDownload`, however I'm not familiar enough with the code and the tests aren't working in my development environment.  There might be cases where `GetImageAliasType` can fail however `GetImage` will not.
```		if args.Secret == "" {
// …
```

OCI image debugging improvements

---

internal/server/scriptlet/load/load.go

Add function checks to scriptlet validation

---

client/incus_instances.go
cmd/incus/console.go
cmd/incusd/instance_console.go
doc/api-extensions.md
doc/rest-api.yaml
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/instance_console.go

This PR introduces a `--force` flag to the console command. When used, it forces the connection and closes any existing ones. Without the flag, the user will receive a message about active connections. This change addresses an issue with Spice/QEMU, where connections are sometimes not properly closed after disconnection.

Add `--force` flag to the console command

---

internal/server/instance/drivers/driver_lxc.go

When running findIdmap to determine the next idmap to use (in isolated mode), instances without an idmap set should be skipped.
This is needed to avoid issues on parallel instance creation on slower storage.
Closes #1483

incusd/instance/lxc: Skip instances without idmap allocation yet

---

internal/server/storage/drivers/generic_vfs.go
internal/server/storage/drivers/utils.go

As we use a sparse writer which will skip any zero blocks, we need to discard (block) or truncate (file) prior to processing the data or we risk having leftover data from a previous snapshot interfere with the new state.
Closes #1264

incusd/storage/drivers/common: Truncate/Discard ahead of sparse write

---

cmd/incusd/instance_console.go

During operation cancellation, the connection may already be closed, so we should check if it's not `nil`. Additionally, errors at this stage are not a concern, as we are making a best-effort attempt to close everything.

Add additional check to Cancel method for ConsoleShow operation

---

internal/server/scriptlet/load/load.go
internal/server/scriptlet/load/utils.go

The error generation function is pretty heavy, but I think the error messages are way nicer this way.
```
root@test-incus:~# incus config set authorization.scriptlet - <<EOF
def get_project_access(project):
return ['ben']
get_instance_access = 3
EOF
Error: cannot set 'authorization.scriptlet' to 'def get_project_access(project):
return ['ben']
get_instance_access = 3
': the function "authorize" is required but has not been found in the scriptlet; additionally, "get_instance_access" should define the scriptlet’s optional function of the same name (found a value of type int instead); finally, the optional function "get_project_access" defines arguments ["project"] (expected ["project_name"])
```

Refactor scriptlet loader and improve checks

---

internal/server/storage/drivers/utils.go

There can be partitions or other artifacts from snapshots which would normally trip blkdiscard. This is fine in our case and it should proceed regardless.
Also not all devices support discard, so treat it as non-fatal.

incusd/storage/drivers: Force blkdiscard and ignore errors

---

internal/server/storage/backend.go

Fixes an issue with live migration between storage pools when snapshots are present.

Fix issue with live-migration between storage pools

---

cmd/incus/network.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/network/driver_ovn.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/zh_Hans.po
shared/api/network.go

Add uplink addresses for OVN network

---

client/incus.go

client: Propagate HTTP TLS dialer to websocket

---

client/oci_images.go

The proxy host address was not inherit to skopoe and as a consequence, it is not possible to connect to proxy to inspect OCI image.
Closes: #1509

client: add proxy host to skopoe inspect

---

internal/server/storage/s3/miniod/miniod.go

Encode and prefix the bucket name as mc has requirements for alias naming.
See @ https://github.com/minio/mc/blob/f4dd5e4a07ffe764f2f489a5f42c4079128e405e/cmd/config.go#L174
This allows - for example - to use incus project names with numbers as first character.

Encode mc alias for storage buckets to match allowed characters

---

internal/server/network/driver_bridge.go
shared/util/boolean.go

dns.mode == none
ipv4.address == none || ipv4.dhcp == false
ipv6.address == none
Fixes #1537

incusd/networks: Tweak dnsmasq startup condition

---

cmd/incus/admin_cluster.go
cmd/incusd/main.go
cmd/incusd/main_cluster.go

"incusd cluster" is typically called by a re-exec of "incus admin cluster".
This was leading to help messages referring to "incusd cluster XYZ" rather than "incus admin cluster XYZ". This commit now adds a bit more logic to detect this situation and correctly alter the command name.

incusd/main_cluster: Tweak to have help refer to correct command name

---

internal/server/device/disk.go

Our disk I/O limits logic was assuming that the disk block device major/minor could be derived from the partition major/minor.
This may still be true on some block device drivers, but in general now, it's common to have a single major shared by multiple drives, making this logic lead to the incorrect device.
Instead we now keep track of partitions when scanning block devices and maintain a map from the partition major/minor back to its parent disk.

incusd/device/disk: Better handle partitions

---

internal/server/storage/drivers/driver_common.go
internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go
internal/server/storage/drivers/utils.go

The way we run QEMU, we always provide 512 byte alignment to the VM, but if the underlying physical storage (on LVM typically) is 4k, we need to make sure that our call to sgdisk doesn't cause it to rewrite the partition table for a 4k alignment.

incusd/storage/drivers: Handle 4k sector sizes

---

cmd/lxd-to-incus/main.go

Don't fail when deleting a table/trigger which is already gone for some reason.

lxd-to-incus: Be more lenient on database changes

---

doc/api-extensions.md
doc/reference/instance_options.md
internal/server/instance/drivers/cfg/cfg.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_bus.go
internal/server/instance/drivers/driver_qemu_config_override.go
internal/server/instance/drivers/driver_qemu_config_test.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/scriptlet/load/load.go
internal/server/scriptlet/qemu.go

Add new `config` hook

---

doc/api-extensions.md
doc/howto/network_acls.md
doc/reference/devices_nic.md
internal/server/device/nic_bridged.go
internal/server/firewall/drivers/drivers_nftables.go
internal/server/firewall/drivers/drivers_nftables_templates.go
internal/server/firewall/drivers/drivers_xtables.go
internal/server/firewall/firewall_interface.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go
internal/server/network/acl/acl_bridge.go
internal/server/network/acl/acl_firewall.go
internal/server/network/acl/acl_load.go
internal/server/network/acl/driver_common.go
internal/version/api.go
test/suites/container_devices_nic_bridged_filtering.sh

Support for ACLs for bridge NIC device when using nftables driver

---

client/incus_instances.go
client/interfaces.go
cmd/incus/debug.go
cmd/incus/main.go
cmd/incusd/api_1.0.go
cmd/incusd/instance_debug.go
cmd/incusd/instances.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/instance_interface.go
internal/version/api.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

- Implement a VM memory dump API
- close #1393 
- OS: Ubuntu 24.04
- Arch: x86_64
**CLI**
```
root@playground:~# incus debug
Description:
Debug commands for instances
Usage:
incus debug [command]
Available Commands:
get-instance-memory Export a virtual machine's memory state
Global Flags:
--debug          Show all debug messages
--force-local    Force using the local unix socket
-h, --help           Print help
--project        Override the source project
-q, --quiet          Don't show progress information
--sub-commands   Use with help or --help to view sub-commands
-v, --verbose        Show all information messages
--version        Print version number
Use "incus debug [command] --help" for more information about a command.
```
**debug instance memory**
```
root@playground:~# incus ls …
```

Implement a VM memory dump API

---

client/incus_server.go
doc/api-extensions.md
doc/howto/initialize.md
doc/rest-api.yaml
internal/version/api.go
shared/api/init.go
test/suites/init_preseed.sh

Add support for configuring storage volumes in preseed init.
In presed init we can now use something like:
```yaml
storage_volumes:
- name: my-vol
pool: my-pool
project:  my-project
```
to create a volume in a pool.
Loosely  related to #1590

incus/init: Add support for storage volumes in preseed init

---

internal/server/instance/drivers/driver_qemu.go

incusd/instance/qemu: Fix device_id warning on 9.2.x

---

cmd/incus-user/main_daemon.go
cmd/incus-user/proxy.go

The logic used to figure out the correct Unix socket path for access to
the demon in `client.ConnectIncusUnix()` was fixed in in
d8b78d5007c01d07b8e7fba78aceb917fbfcf879 to account for use of
/run/incus/unix.socket as an alternative socket location. However, the
proxying code of incus-user was not updated when the fix was
introduced. As a result, even if initial connection to the server and
the configuration queries were successful, the actual attempt to proxy
a client request would fail while trying to connect to
/var/lib/incus/unix.socket regardless of prior findings.

incus-user: keep track of socket path used to connect to the server

---

cmd/incus-user/main.go
cmd/incus-user/main_daemon.go

Refactor logging setup so that it matches the rest of the code base. Add support for --verbose and --debug, similarly to other commands.

incus-user: unify logging, support --verbose and --debug

---

client/incus_server.go
cmd/incus/admin_init_auto.go
cmd/incus/admin_init_dump.go
cmd/incus/admin_init_interactive.go
doc/api-extensions.md
doc/rest-api.yaml
internal/version/api.go
shared/api/init.go

Add project support to profiles in preseed init.
Allow initialize lxd with  profiles for different projects.
Because of the need to handle projects I have changed `createProfile` and `updateProfile` to `applyProfile` that checks if the profile already exists in the specific project.
Fixes #1590

Add project support to profiles in preseed init

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go

This adds IOMMU support for guests that aren't running Windows and on platforms that support IOMMU and PCI.
Closes #1643

incusd/instance/drivers/qemu: Add IOMMU device

---

internal/server/instance/drivers/driver_common.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go

This PR fixes the assignment of `volatile.cpu.nodes` when `limits.cpu` is used alongside `limits.cpu.nodes=balanced`, and `limits.cpu` exceeds the number of CPUs available per NUMA node.
Previously, `volatile.cpu.nodes` was always set to a single NUMA node, even when more were required. With this fix, it can now span multiple NUMA nodes when necessary.

incusd/instance/drivers: Improve NUMA balancing

---

internal/server/device/nic_macvlan.go
internal/server/ip/link.go
internal/server/network/driver_bridge.go

The previous code relied purely on the name of the device to decide if a device should be deleted which was not correct and could result in the deletion of unwanted devices. The new code ensures that the device is part of the bridge and that its kind is correct before deleting it.

incusd/network/bridge: Fix deletion of tunnels and dummy devices

---

.github/workflows/tests.yml
doc/.wordlist.txt
doc/api-extensions.md
doc/reference/devices_nic.md
internal/server/device/device_utils_network.go
internal/server/device/nic_routed.go
internal/server/ip/link_veth.go
internal/server/ip/route.go
internal/server/ip/tuntap.go
internal/version/api.go
test/suites/container_devices_nic_routed.sh

See #1613 
I sadly did not get the test-suite to work yet but tried to test manually as good as possible.
Also testing the feature for VMs was not possible for me yet.

Add `vrf` parameter for routed-nic devices

---

cmd/incusd/instance_snapshot.go
cmd/incusd/instances_post.go

Copying an instance with the `--refresh` flag sometimes fails due to instance name validation errors.
Do not set the `Name` field in `api.InstancePost` or `api.InstanceSnapshotPost` structs, as this field is meant only for renaming instances.
Fixes: #1629

Fix instance copy error when using '--refresh' flag

---

doc/.wordlist.txt
doc/howto/network_load_balancers.md

The option "listen port" does not exist on backends, only on ports. The sentence about what happens if no target port is specified doesn't make any sense I think, but I also don't know what the actual behaviour in that case is.

Fix docs for load balancer create backend

---

internal/server/instance/drivers/driver_qemu.go

This additional check ensures that migrations are not performed on local disks. On remote disks, the migration effectively only mounts the disk on the target node.
Fixes: #1657

Check if disk is remote when migrating with an extra disk

---

client/oci_images.go

Currently, incus uses skopeo to copy a docker image to an oci formatted file tree. The OCI:/ endpoint does not support copying signatures. Several projects are using cosign or gpg to sign their images which the OCI:/ endpoint does not support. This adds the flag to skopeo to not attempt to copy the unsupported signatures as a bandaid until a different method that supports signatures is identified.

fix: Don't attempt to download signatures for oci

---

internal/server/storage/drivers/generic_vfs.go
internal/server/storage/drivers/utils.go

During custom volume migration from LVM to a dir pool, the block file may be smaller because trailing zeros are omitted when creating the sparse file, and truncation is not performed. This change ensures the block file matches the source volume size by applying truncation.
Fixes: #1676

Truncate the block file during custom volume migration

---

internal/server/device/device_utils_disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/storage/drivers/driver_cephfs.go
internal/server/storage/drivers/driver_cephfs_utils.go
internal/server/storage/drivers/utils_ceph.go

In continuation of #1473 it is now approaching completion. It passes the full test suite, in addition incusd now can use ceph on my own cluster where previously it could not. 
Also initial tests seem to indicate it fixes #1023: 
```
user@host ~> incus storage show ceph
config:
cephfs.cluster_name: ceph
cephfs.path: cephfs/volumes/test-group/test-subvol/e8459ffc-ac7e-41de-bb96-aaef2ee0e8b5
cephfs.user.name: admin
source: cephfs/volumes/test-group/test-subvol/e8459ffc-ac7e-41de-bb96-aaef2ee0e8b5
description: ""
name: ceph
driver: cephfs
used_by: []
status: Created
locations:
- none
```
Remaining is to write a few tests to capture some of the additional Ceph superpowers and to squash the whole mess of commits down.
With that in mind, comments and concerns are now very much welcome

Ceph refactor

---

cmd/incusd/api_project.go
cmd/incusd/certificates.go
cmd/incusd/network_acls.go
cmd/incusd/network_forwards.go
cmd/incusd/network_integrations.go
cmd/incusd/network_load_balancers.go
cmd/incusd/network_peers.go
cmd/incusd/network_zones.go
cmd/incusd/network_zones_records.go
cmd/incusd/networks.go
cmd/incusd/profiles.go
cmd/incusd/storage_buckets.go
cmd/incusd/storage_pools.go
doc/api-extensions.md
doc/rest-api.md
doc/rest-api.yaml
internal/filter/value.go
internal/version/api.go
test/suites/filtering.sh

This PR aims to make odata-like filtering available for all collection endpoints (see #1674). 
So far I have only implemented it for `/1.0/networks`, could someone take a quick look and tell me if the way I'm doing this is alright, before I work on the other endpoints?
Closes #1674

Add filtering to all API collections

---

internal/server/instance/drivers/driver_lxc.go

Docker uses the range `0 2147483647` for the ping group IDs, but that fails if not that many groups are available, and the default incus configuration only allocates 1000000000 IDs, so I opted for a more conservative `0 65536`.
I suppose ideally we would check what ID range is available and use that, but I couldn't figure out how.

Allow ICMP and low ports for unprivileged users in OCI containers

---

cmd/incusd/migrate_storage_volumes.go
internal/migration/utils.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/migration/migration_volumes.go
internal/server/storage/backend.go
internal/server/storage/drivers/driver_btrfs_volumes.go
internal/server/storage/drivers/driver_ceph_volumes.go
internal/server/storage/drivers/driver_cephfs_volumes.go
internal/server/storage/drivers/driver_zfs_volumes.go
internal/server/storage/drivers/generic_vfs.go
internal/server/storage/drivers/utils.go
internal/server/storage/utils.go

This is a follow-up to #1696 addressing cases where resizing a parent volume can also resize its snapshots, but the updated snapshot size is not properly communicated.
This PR ensures that snapshot size information is correctly transmitted, allowing sparse files to be truncated properly. Additionally:
- Volume size information is now included in certain cases.
- The `enlargeVolumeBlockFile` function is called whenever volume size information is provided.

Fix snapshot size handling in cross-pool copy/move

---

internal/server/apparmor/instance.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/edk2/driver_edk2.go
internal/server/instance/drivers/edk2/driver_edk2_test.go

Current INCUS_EDK2_PATH once set, no matter it's directory exists or not, it will overwrite the buildin EDK2 Path. The fix added two conditions to overwrite:
1. buildit EDK2 Path directory not exist, and
2. INCUS_EDK2_PATH directory exists.
And a function naming issue is fixed too(GetAchitectureFirmwarePairs -> GetArchitectureFirmwarePairs).

Fixed incus edk2 path overwrite issue

---

cmd/incusd/instance_instance_types.go
doc/environment.md

and environment INCUS_SKIP_INSTANCE_TYPES set to true, because most enterprise
environment has no internet access, so they can put instance types in cache and
set `INCUS_SKIP_INSTANCE_TYPES = true`.

Do not download instance types if cache loadable

---

internal/server/network/driver_ovn.go

Currently DHCP in OVN networks is configured to advertise the uplink DNS address, if an uplink exists. OVN networks with the `network=none` option don't get any DNS server over DHCP. 
Since OVN has its own DNS server, we can just use the OVN router IP. 
I don't understand why this isn't used in general, and how the uplink DNS even gets the correct information, but at least for isolated networks I think it makes sense to use OVN for the DNS server.

Fix DNS for isolated OVN networks

---

.github/workflows/tests.yml
cmd/incusd/main_forknet.go
doc/.wordlist.txt
doc/api-extensions.md
doc/reference/network_bridge.md
doc/reference/network_ovn.md
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go
internal/version/api.go
shared/validate/validate.go
test/main.sh
test/suites/network_dhcp_routes.sh

This PR adds a new option `ipv4.dhcp.static-routes` for both bridge and ovn networks. The value of the option is directly passed through to dnsmasq and ovsdb respectively, to be used as DHCP option 121.

Allow announcing extra routes through DHCPv4

---

cmd/generate-database/db/constants.go
cmd/generate-database/db/method.go
internal/server/db/cluster/certificate_projects.mapper.go
internal/server/db/cluster/certificates.mapper.go
internal/server/db/cluster/cluster_groups.mapper.go
internal/server/db/cluster/config.mapper.go
internal/server/db/cluster/devices.mapper.go
internal/server/db/cluster/instance_profiles.mapper.go
internal/server/db/cluster/instances.mapper.go
internal/server/db/cluster/networks_integrations.mapper.go
internal/server/db/cluster/nodes_cluster_groups.mapper.go
internal/server/db/cluster/operations.mapper.go
internal/server/db/cluster/profiles.mapper.go
internal/server/db/cluster/projects.mapper.go
internal/server/db/cluster/snapshots.mapper.go

* Handle constraint error in Create methods
* Ensure a commit-able db connection (DB transaction) is passed to methods which perform multiple DB operations.

generate-database: Handle non tx DB connections

---

cmd/incus/file.go

Changes the `incus file edit` command to use the file extension of the edited file for the temp file, if there is any, so that editors can deduce the file type from it and use correct syntax highlighting.

incus file edit extension

---

internal/server/storage/drivers/driver_zfs_volumes.go

_The issue was first reported by TrueNAS 25.04 beta test users. TrueNAS 25.04 includes Incus as a major feature_
When the ZFS driver's CreateVolume function is unable to create the desired volume due to the existence of a pre-existing dataset, it would fail and proceed to recursively destroy the pre-existing dataset, potentially leading to unexpected data loss.
This has occurred to users who have been experimenting with trying to "import" their existing zvols into an incus zfs storage pool.
All other drivers were surveyed and they do not erase pre-existing data on failure, unless they first succeed in creating a volume or directory. The user is then responsible for correcting the situation in order to enable the CreateVolume call to succeed
The fix splits and moves the current …

incusd/storage/zfs: Fix ZFS CreateVolume deletes pre-existing data on failure

---

cmd/incus/file.go
internal/server/instance/drivers/driver_lxc.go

This works around a Go sftp bug that may lead to partial read/write.

incus/file: Always use 1MB chunks for SFTP

---

internal/server/acme/acme.go

The path used in #1753 is incorrect, and certificates should be being loaded from the `certificates` subfolder. This PR fixes this issue.

Use the correct path for ingesting DNS-01 challenge certificate outputs

---

cmd/incusd/api_1.0.go
cmd/incusd/daemon.go
internal/server/bgp/server.go

This simplifies the BGP package a bit and improves on the ability to reconfigure it.
The go-bgp ability to start/stop the daemon doesn't work reliably, so we need to spawn a completely new listener instead.
This moves Start/Stop interactions to the main Reconfigure option and makes sure to always feed all peers and prefixes on startup.

incusd/bgp: Rework start/stop logic

---

cmd/incus/copy.go

Addresses topic discussed in #1751 - makes `type=none` drop any further device properties, except for type=none itself.

make `incus copy --device xx,type=none` drop remaining device properties

---

doc/.wordlist.txt
doc/howto/instances_create.md
internal/server/instance/drivers/driver_qemu.go

incusd/instance/qemu: rtc base localtime for windows

---

doc/.wordlist.txt
doc/api-extensions.md
doc/reference/network_bridge.md
doc/reference/network_ovn.md
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go
internal/version/api.go

This PR adds two options, `ipv4.dhcp.dns` and `ipv6.dhcp.dns` for both bridge and OVN networks. The values of these options are used as option 6 in dhcp4 and option 23 in dhcp6 respectively, i.e. advertising DNS servers to DHCP clients. The values in `ipv6.dhcp.dns` are also sent as RDNSS in router advertisements by dnsmasq on bridge interfaces, and the first value is configured for router advertisements in OVN (it only supports a single RDNSS value for RA).
If the options are not set, then the current behaviour (dnsmasq advertises itself and OVN networks use whatever their uplink provides) is used.

Add option to configure DNS server for bridge and OVN networks

---

doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/instance/drivers/qmp/commands.go
internal/server/metadata/configuration.json

When live-migrating to a newer QEMU, the base `q35` definition is likely to have evolved.
QEMU requires the source and target machine definition to match up, so keep track of the machine definition in a volatile key and ensure that the target starts with the correct machine definition.

Handle live migration between QEMU versions

---

cmd/incus/file.go

Not too sure why we were using Split rather than Dir given we were discarding the Base part of the path. But it looks like Split gets a bit confused by relative parent paths (..) whereas Dir doesn't.
Closes #1808

incus/file: Properly handle relative source paths

---

cmd/incus/storage.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

The storage command on CLI has the following examples:
incus create storage s1 dir
incus create storage s1 dir < config.yaml
This is wrong syntax because incus create is used for creating VMs and not storage, the examples should present incus storage create instead.

cmd/storage:  incorrect CLI syntax in storage pool creation examples

---

doc/api-extensions.md
doc/rest-api.yaml
internal/server/cgroup/abstraction.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/version/api.go
shared/api/instance_state.go
test/suites/basic.sh

Add allocated CPU time to instance state

---

doc/api-extensions.md
doc/reference/devices_nic.md
internal/server/device/config/device_runconfig.go
internal/server/device/nic.go
internal/server/device/nic_bridged.go
internal/server/device/nic_macvlan.go
internal/server/device/nic_p2p.go
internal/server/device/nic_routed.go
internal/server/instance/drivers/driver_qemu.go
internal/version/api.go

This PR allows to use USB emulation for NICs through an `io.bus` device option.
It introduces a `UseUSBBus` field to the `RunConfig` struct, which may also help for #1697

Add support for USB NICs

---

internal/server/storage/s3/miniod/miniod.go

minio cli `mc` is conflict with midnight commander `/usr/bin/mc` so add more possible candidates `miniocli` and `minioc` to search list, and put `mc` in lowest priority.

incusd/storage/s3 Fixed minio client mc too ambious issue

---

cmd/generate-database/db/method.go

Currently fails the new-line after block requirement.

cmd/generate-database/db: Fix GetNames spacing

---

internal/server/storage/s3/miniod/admin_client.go
internal/server/storage/s3/miniod/miniod.go

Building on #1821, add `minio-client` to the list of potential MinIO client binaries, and update logic in admin_client.go to match changes in miniod.go.

Extend minio client naming

---

doc/api-extensions.md
doc/config_options.txt
internal/server/device/disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/metadata/configuration.json
internal/version/api.go

Add `io.bus=usb` for disks

---

.golangci.yml

Some of the CI tools occasionally break with older Go versions and the static analysis result shouldn't depend on Go versions anyway.

golangci: Upgrade to version 2

---

internal/server/network/driver_ovn.go

This was added thinking it would be desirable for OVN-IC environments, but feedback is that production OVN-IC users prefer that traffic to go through an external path.
Given that, remove the logic and if the needs come back, we'll handled it through an interconnection option so this can be configurable for a particular environment.

incusd/network/ovn: Remove internal routes to forward/load-balancers

---

doc/reference/storage_linstor.md
internal/server/storage/drivers/driver_linstor_utils.go
internal/server/storage/drivers/driver_linstor_volumes.go
test/suites/storage_driver_linstor.sh

Adds a `linstor.remove_snapshots` volume config option that behaves similarly to the `zfs.remove_snapshots` option. Since LINSTOR also has the limitation of not being able to restore intermediate snapshots, I think it makes sense to have a similar config option to automatically delete old snapshots when needed.

Add `linstor.remove_snapshots` config option

---

cmd/incusd/instance.go
doc/api-extensions.md
doc/config_options.txt
internal/instance/config.go
internal/server/instance/drivers/driver_lxc.go
internal/server/metadata/configuration.json
internal/version/api.go

Closes #1558.
@stgraber do we need an API extension for this?

OCI entrypoint configuration

---

cmd/incus/image.go
cmd/incus/list.go
cmd/incus/list_test.go
cmd/incus/utils.go
cmd/incus/utils_test.go

This PR introduces the following changes:
- Added a parameter (`singleValueServerSupport`) to `getServerSupportedFilters`. This new parameter determines whether single-value filters should be handled by the server or the client. Images use single-value filters to filter by aliases and fingerprints, which can be more complex to implement on the server side. Since image filtering is less critical compared to instances, handling this on the client side is acceptable.
- Introduced `modifySingleValueFilters`. This function prepares single-value filters into a format that is accepted by the server.
- Fixed duplicate filters issue - resolved a bug where duplicate filters were being added to the filters slice.

Add support for server-side filtering by instance name

---

internal/server/instance/drivers/driver_lxc.go

incusd/instance/lxc: Fix max gid when in a privileged container

---

doc/config_options.txt
internal/server/device/disk.go
internal/server/metadata/configuration.json

Currently the documentation for the `path` option says it is only available for containers. It is available for custom filesystem volumes on VMs as well, and I assume also for ceph filesystem mounts on VMs.

Docs: correct restriction on `path` option

---

client/incus_images.go
client/interfaces.go
client/oci_images.go
client/simplestreams_images.go
cmd/incus/image.go

Currently, filtering cannot be used together with the `all-projects` flag when listing images.
This PR introduces `GetImagesAllProjectsWithFilter`, allowing image filtering while the `all-projects` flag is enabled.

Enable filtering with the `all-projects` flag when listing images

---

internal/server/instance/drivers/driver_common.go

When multiple restarts occur at the same time, we need to wait for the ongoing one to complete rather than call Start multiple times in parallel.

incusd/instance/common: Fix concurrent restarts

---

cmd/incusd/main_forknet.go

RFC 3442 requires that the Router option is ignored if the Classless Static Routes is provided and supported. I didn't realise that when I originally added the feature.

RFC 3442 compliance in forknet dhcp client

---

cmd/incusd/operations.go

We were incorrectly returning a partial operation update when an operation would fail rather than match the get behavior.
Part of #1889

incusd/operations: Fix WaitGet on op failure

---

cmd/incusd/instance_snapshot.go
internal/server/instance/drivers/driver_common.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go
internal/server/response/swagger.go
internal/server/storage/backend.go
internal/server/storage/backend_mock.go
internal/server/storage/drivers/driver_common.go
internal/server/storage/drivers/driver_zfs.go
internal/server/storage/drivers/driver_zfs_volumes.go
internal/server/storage/drivers/interface.go
internal/server/storage/pool_interface.go
internal/server/storage/utils.go

This adds some logic to allow storage drivers to implement snapshot data pre-fetching.
In the case of ZFS, we're pulling all the usage data in one bulk query.
When running with a LOT of snapshots, this can cause rather extreme time savings:
```
root@u24:~# time incus snapshot list a01 >/dev/null
real	3m15.907s
user	0m0.791s
sys	0m0.489s
root@u24:~# time incus snapshot list a01 >/dev/null
real	0m3.911s
user	0m0.737s
sys	0m0.270s
```
The first run here is with the old logic, the second run is with the new logic in place.
In this particular case, I had 6000 snapshots on that one container.

Add snapshot pre-fetching support

---

client/incus.go

Fixes "non-constant format string" errors in fmt calls.

client/incus: Fix non-constant format strings

---

doc/.wordlist.txt
doc/howto/cluster_access.md

This PR proposes an mDNS based setup for cluster high availability docs.
Ref: https://datatracker.ietf.org/doc/html/rfc6762

docs: mDNS setup for cluster HA

---

cmd/incus/storage_volume.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

This change adds support for filtering storage volumes using a single keyword.
Example:
`storage volumes ls default vol` will return all volumes from the "default" storage that start with `vol`.
Regular expressions are also supported, e.g., `vol.*`.

Support filtering storage volumes by a single keyword

---

doc/config_options.txt
doc/reference/network_bridge.md
internal/server/metadata/configuration.json
internal/server/network/driver_bridge.go

Resolves #1792 
Ran `make doc-spellcheck` and it dinged me for having "vxlan", "dns", and "openvswitch". However I assume this is okay given that these words are also found in the documentation on the site.
Signed-off-by: Nathan Chase <ntc477@utexas.edu> & Noor Ali <noorali05@utexas.edu>

Add generated documentation for network bridge

---

doc/tutorial/first_steps.md

I've wanted to copy paste this a couple of times, but it's a little inconvenient because of the placeholder.
Replace it with a standard environment variable (looks like it's part of POSIX).
Signed-off-by: Brendan Jackman <jackmanb@google.com>

doc: Use `$USER` instead of YOUR-USERNAME

---

internal/server/instance/drivers/driver_lxc.go

Older kernels don't properly namespace this sysctl, leading to startup failures. This kernel change is required for it to work as intended: https://lkml.org/lkml/2023/5/31/547
Closes #1933

incusd/instance/lxc: Restrict unprivileged ping to recent kernels

---

doc/.wordlist.txt
doc/api-extensions.md
doc/howto/network_forwards.md
doc/rest-api.yaml
internal/server/firewall/drivers/drivers_consts.go
internal/server/firewall/drivers/drivers_nftables.go
internal/server/firewall/drivers/drivers_nftables_templates.go
internal/server/firewall/drivers/drivers_xtables.go
internal/server/network/driver_bridge.go
internal/server/network/driver_common.go
internal/version/api.go
shared/api/network_forward.go

This is primarily meant for environments where a single IP address is mapped to multiple instances using large port ranges with differing source and target ranges.
In that scenario, if the target is to initiate an outgoing connection, the desired behavior is for the external address to be that of the forward and for the external port to be mapped according to the mapping in the forward rule.

Implement SNAT as part of network forwards

---

internal/server/apparmor/instance_lxc.profile.go

Bubblewrap [2], used by Flatpak [3], attempts to disable further userns creation by writing 1 to `/proc/sys/user/max_user_namespaces` in a new userns, but this fails in a fresh unprivileged Incus container. This is safe even outside Bubblewrap's new userns because the files in `/proc/sys/user` are "the limits for the user namespace in which the opening process resides," [1] which is the Incus-created userns for the unprivileged container.
Reproduce:
```bash
incus launch -c security.nesting=true images:ubuntu/24.04 ubu
incus shell ubu
apt install bubblewrap
bwrap --unshare-user --disable-userns nothing
#=> bwrap: cannot open /proc/sys/user/max_user_namespaces: Permission denied
bwrap --unshare-user --disable-userns nothing
#=> bwrap: execvp nothing: No such file or directory
```
See:
[1] …

incusd/apparmor/lxc: Allow write access to /proc/sys/user

---

internal/server/instance/drivers/driver_lxc.go

That way the scheduler call will happen after any database changes have been committed, avoid a race where the scheduler runs so quickly that the new value hasn't made it into the database yet.
There's no risk in moving this to a defer as the scheduler call was already non-blocking.
Closes #1936

incusd/instance/lxc: Defer calls to the scheduler

---

shared/archive/archive.go

When unpacking a SquashFS containing `security.selinux` xattrs, the AppArmor archive profile blocks access to writing these to the FS which crashes unsquashfs (but not tar).
Errors seen:
* unsquashfs: `FATAL ERROR: write_xattr: failed to write xattr security.selinux for file squashfs-root/etc/selinux/targeted/contexts/files/file_contexts because Operation not permitted`
* AA denials: `apparmor="DENIED" operation="capable" class="cap" profile="incus_archive-cf1435b8-7543-419a-87a1-f656442c6e2f" pid=928 comm="unsquashfs" capability=21  capname="sys_admin"` (similar for tar)
I'm not sure my changes are the correct solution for this behavior. I can think of several more:
* Use the `-xattrs-exclude ^security.` to narrow down xattr exclusion (but only works for unsquashfs v4.6+)
* Ignore errors …

shared/archive: Prevent xattr errors from crashing unsquashfs

---

cmd/incus-simplestreams/main_add.go
cmd/incus-simplestreams/main_remove.go
cmd/incus/delete.go

Add `import` and `delete` aliases to `incus-simplestream add/remove` and `remove` alias to `incus delete`

Add common aliases for add/create remove/delete/rm in the CLI

---

internal/server/util/http.go
test/suites/tls2jwt.sh

This update enhances the `CheckJwtToken` function to support scenarios where the JWT token is provided via the `access_token` query parameter instead of the Authorization header.
🔧 Fixes: #1932 
Changes:
- Attempts to extract the token from the Authorization header first (Bearer <token>)
- Falls back to `access_token` query parameter if the header is missing or invalid
- Maintains existing JWT validation: expiration, not-before, and signature verification
- This fix provides compatibility for clients that cannot set headers, such as certain browser-based tools or embedded clients.

feat: support access_token query parameter as JWT fallback

---

doc/api-extensions.md
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_config_test.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/util.go
internal/server/instance/drivers/util_test.go
internal/version/api.go

This PR adds support for hot-plugging memory during VM runtime.
It reuses the same approach and set of functions that are used for generating QEMU CPU and memory configurations. The generated configuration is then translated into a format compatible with QMP. This approach respects both hugepages and NUMA node topology.
Closes: #986

Memory hotplug support for VMs

---

cmd/incusd/images.go
cmd/incusd/instance.go
cmd/incusd/instance_access.go
cmd/incusd/instance_backup.go
cmd/incusd/instance_console.go
cmd/incusd/instance_debug.go
cmd/incusd/instance_delete.go
cmd/incusd/instance_exec.go
cmd/incusd/instance_file.go
cmd/incusd/instance_get.go
cmd/incusd/instance_logs.go
cmd/incusd/instance_metadata.go
cmd/incusd/instance_patch.go
cmd/incusd/instance_post.go
cmd/incusd/instance_put.go
cmd/incusd/instance_rebuild.go
cmd/incusd/instance_sftp.go
cmd/incusd/instance_snapshot.go
cmd/incusd/instance_state.go
cmd/incusd/instances_get.go
cmd/incusd/instances_post.go
cmd/incusd/response.go
cmd/incusd/storage_volumes_state.go
internal/server/cluster/connect.go
internal/server/db/instances.go
internal/server/db/instances_test.go
internal/server/storage/backend.go

Incus never had the old /1.0/containers and /1.0/virtual-machines routes, it's therefore a waste of time for every API endpoint to do extra request parsing and pass through the result of that operation (which will always be instancetype.Any).

incusd: Remove old routing logic

---

go.mod
go.sum
internal/server/sys/apparmor.go
internal/server/sys/apparmor_test.go

package `github.com/syndtr/gocapability` has stayed for long time without update or bug fix, and incus use little function it provides.

Remove gocapability dependency

---

doc/config_options.txt
doc/reference/devices_infiniband.md
internal/server/device/device_load.go
internal/server/device/infiniband_physical.go
internal/server/metadata/configuration.json

The previous Infiniband device documentation used a static table of valid options. This was moved to an auto-generated table using gendoc. We closed our old PR and created this new one.
https://github.com/lxc/incus/issues/1787

Infiniband Device Documentation Ported to GenDoc

---

cmd/incusd/main_forknet.go

Systemd-networkd (and probably others) adds dhcp static routes via `0.0.0.0` with link scope, which is arguably the only reasonable thing to do with them and allows configuring later routes via those routes, e.g. `192.168.0.2/32,0.0.0.0,10.0.0.0/8,192.168.0.2` to configure `192.168.0.2/32` on the link itself and `10.0.0.0/8` via `192.168.0.2`. 
The `ip route` command uses link scope when called like `ip route add dev eth0 192.168.0.2/32` but not when called like `ip route add dev eth0 192.168.0.2/32 via 0.0.0.0`.

Add dhcp static routes via 0.0.0.0 with link scope in forknet

---

client/incus_profiles.go
client/interfaces.go
cmd/incus/profile.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

Resolves #1910
Adds server-side filtering for the `incus profile list` command.
Filters are either:
- **a string**, which filters the names of profiles
(e.g. `incus profile list foo` lists all profile names that start with `foo`)
- **a list of  `<key>=<value>` pairs** delimited by a comma `,`, which filters by profile properties.
(e,g, `incus profile list description=foobar.*` lists all profiles with a description that starts with `foobar`)

Add server side filtering for `incus profile list`

---

cmd/incus-agent/templates.go
cmd/incus/utils_properties_test.go
cmd/incus/utils_test.go
cmd/incusd/api_cluster_evacuation.go
cmd/incusd/instance_test.go
cmd/incusd/snapshot_common_test.go
internal/cmd/sort_test.go
internal/instancewriter/instance_tar_writer.go
internal/server/auth/authorization_objects_test.go
internal/server/db/db_internal_test.go
internal/server/dns/handler.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/version/version_test.go
shared/cliconfig/file.go
shared/osarch/release_test.go
shared/util/struct.go

For example:
metadata := new(api.ImageMetadata) // type: *api.ImageMetadata
err = yaml.Unmarshal(content, &metadata)
It works on `yaml.v2` and `yaml.v3` but not work under `goccy/go-yaml`, and `goccy/go-yaml` behavior is correct. So fixed it and add test cases to pretect.

Fix reference passing when yaml unmarshal

---

doc/config_options.txt
internal/server/metadata/configuration.json
internal/server/network/driver_bridge.go

It was changed from "IPv4 address" to "all addresses" in
https://github.com/lxc/incus/commit/70897e34e459f53e3ef1b189cc84706546e9aca1#diff-ea939356d9c610505874f52d8134c991919241ef130a0d667572db54ce8ded46L77 and
https://github.com/lxc/incus/commit/47599d89620f930d7423f0a2252651504ad7e969#diff-5f4225b439a90e9d63cf9e7463cb3c8ae433e26a64e277494cbc124c97dee6daR1734
I think it was a mistake.

doc: Fix default value of ipv4.dhcp.gateway to IPv4 address

---

doc/config_options.txt
internal/server/metadata/configuration.json
internal/server/network/driver_bridge.go

It was changed from "IPv6 address" to "IPv6"
in
https://github.com/lxc/incus/commit/70897e34e459f53e3ef1b189cc84706546e9aca1#diff-ea939356d9c610505874f52d8134c991919241ef130a0d667572db54ce8ded46L97 and
https://github.com/lxc/incus/commit/47599d89620f930d7423f0a2252651504ad7e969#diff-5f4225b439a90e9d63cf9e7463cb3c8ae433e26a64e277494cbc124c97dee6daR1893
I think it was a mistake.

doc: Fix default value of ipv6.routes network_bridge

---

client/util.go
cmd/incusd/devices.go
cmd/incusd/main_cluster.go
internal/server/config/safe.go
internal/server/events/connections.go
internal/server/instance/drivers/driver_qemu_templates.go
internal/server/network/network_utils.go
internal/version/version.go

Renames some variables that were shadowing builtin go functions or interfaces.
I did not rename all the variables i found, since some are a bit harder to understand.

Rename vars using builtin names

---

internal/server/cluster/heartbeat.go

Refactors getting the heartbeat mode name into a function. The original code did not cover all cases.

incusd: Refactor getting heartbeat mode name into a function

---

cmd/generate-database/db/mapping.go
cmd/generate-database/db/stmt.go
internal/server/dns/handler.go
internal/server/storage/drivers/driver_zfs.go
shared/api/instance.go

This PR unifies the usage of a few structs that had a mixture of pointer and non pointer recievers.
This PR does not contain any changes to the ErrorList or the Volume struct, since these seem too big for this PR and should be done in their own PRs (if at all).

Unify receiver types 

---

internal/server/network/driver_ovn.go

In some busy environments, the 2.5s timeout wasn't quite enough.
Sponsored-by: Luizalabs (https://luizalabs.com)

incusd/network/ovn: Wait up to 10s for OVN northd to allocate an IP

---

internal/server/network/driver_bridge.go

Refactors a wrong err check where err was checked but err2 should have been checked.

incusd: refactor process kill error being ignored

---

internal/server/instance/drivers/qmp/commands.go

Refactors a wrong for loop where a qemu device is being looked up. The loop started by setting `deviceFound` to true instead of false.

incusd/instance: fix device finding logic

---

cmd/incusd/api_internal.go

This PR removes unrechable code in cmd/incud/api_internal.go and also updates an outdated comment .

incusd: remove unreachable code in api internal

---

cmd/incus/admin_init.go

Refactors the initialization code for the config in admin_init.go. This switch case based approach represents the intention of the if chain, since the cases are exclusive.

incus: refactor admin_init.go config initialization

---

client/incus_storage_volumes.go
client/interfaces.go
cmd/incus-migrate/main_migrate.go
cmd/incus-migrate/transfer.go
cmd/incus-migrate/utils.go
cmd/incusd/migrate.go
cmd/incusd/migrate_storage_volumes.go

Extend incus-migrate to support uploading filesystems and disks as custom volumes

---

client/incus_projects.go
client/interfaces.go
cmd/incus/project.go

Resolves #1911
Adds server-side filtering for `incus project list`. Filters are either a string to filter by exact name of projects or a list of  <key>=<value> pairs separated by commas to filter by properties.

Add server-side filtering for `incus project list`

---

doc/config_options.txt
doc/reference/network_ovn.md
internal/server/metadata/configuration.json
internal/server/network/driver_ovn.go

This PR closes #1794. Automated table towards OVN network documentation by utilizing config metadata.

Port ovn network documentation to gendoc 

---

go.mod
go.sum
internal/server/endpoints/endpoints.go

`gopkg.in/tomb.v2` is inactive for long time and incus use less function of it.

Remove gopkg.in/tomb.v2 dependency

---

doc/api-extensions.md
doc/config_options.txt
internal/server/device/nic_routed.go
internal/server/metadata/configuration.json
internal/server/network/driver_ovn.go
internal/server/network/driver_physical.go
internal/version/api.go

We closed our old PR (https://github.com/lxc/incus/pull/1964) and are opening a new one due to it being pretty outdated compared to the codebase. We added our changes to nic_routed.go and wanted to know where else we need to edit. We assume the documentation we need to add would be through gendoc and we would mark the ipv4.host_table and ipv6.host_table as deprecated there.
Issue #1559

incusd/server/device/nic_routed: Added host_tables

---

cmd/incus-agent/dev_incus.go
cmd/incus-agent/server.go
cmd/incusd/api.go
cmd/incusd/dev_incus.go

This PR renames the result of calling `mux.newRouter()` from `mux` (which collides with the package name `mux`) to `router` which should fit with the method name. 
This PR also renames other variables that used to called `m` to `router`, so that they are the same.
If desired i can also just rename them all to `m`.

Rename result of `mux.NewRouter()` so they dont collide with the mux package

---

client/incus_images.go
cmd/incusd/daemon_images.go
cmd/incusd/images.go
internal/server/apparmor/apparmor.go
internal/server/instance/drivers/driver_qemu.go
internal/server/util/http.go

This PR renames all instances of `sha256.New()` to `hash256` so that they do not collide with the package name `sha256` anymore. I chose this variable name since that was already used a bunch in other places. I am willing to use a different name of course, but i thought, i'd use what was already there.

Rename instances of sha256.New() so they dont collide with the package name

---

cmd/incus-migrate/main_migrate.go
internal/filter/value.go
internal/server/db/operationtype/operation_type.go
internal/server/scriptlet/marshal/marshal.go

This PR ensures that switch statements on iota constants cover all cases internally either by internalizing the external return statement as a default case or by commenting explicitely that a certain case is ignored. The file `vdpa.go` is ignored in this PR, since that looks like it needs special taking care of.

Missing case statements for iota constants

---

cmd/incusd/api_1.0.go
internal/server/config/errors.go
internal/server/config/errors_internal_test.go
internal/server/config/map.go
internal/server/config/safe.go

This PR refactors the ErrorList struct and the Error struct in internal/server/config/errors.go so that the Error struct is now private and all functions declared on ErrorList have the same type of receiver.
Also refactors the implementation of the error interface on ErrorList and adds a bunch of new tests for it.

incusd: Refactor error list

---

internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_config_override.go
internal/server/instance/drivers/driver_qemu_config_test.go

This PR rewrites the old QEMU config override logic to save some CPU cycles and to be a little easier to review. This breaks the previous behavior in the following way: new config sections are inserted in the final config in the order in which they are seen, not in the order in which they are last updated. I feel like it’s actually the intended behavior (as it’s the one for already-defined sections, not new ones).

Rework QEMU config override logic

---

internal/server/dnsmasq/dhcpalloc/dhcpalloc.go
internal/server/dnsmasq/dhcpalloc/dhcpalloc_test.go

Refactors the DHCPValidIP condition checks. The way it was written had a redundant else branch to check the `inSubnet` variable.

incusd/dnsmasq: refactor DHCPValidIP condition checks

---

cmd/incusd/instance_state.go
cmd/incusd/instances_put.go

Renames the function instanceActionToOptype to fix a typo. Also move the default case into the switch.

incusd: rename instanceActionToOptype to instanceActionToOpType

---

internal/iprange/range_test.go

Adds tests for the ContainsIp and String methods on the iprange.Range struct type.

internal/iprange: add tests for the iprange.Range struct

---

doc/config_options.txt
doc/reference/network_macvlan.md
internal/server/metadata/configuration.json
internal/server/network/driver_macvlan.go

Port macvlan network documentation to gendoc

---

internal/server/instance/drivers/driver_qemu_metrics.go

This prevents a metrics overflow as QEMU may be reporting slightly higher memory usage than the user configured limit (due to QEMU's own consumption).
Closes #1686

incusd/instance/qemu: Don't allow QEMU RSS to exceed memory limit

---

client/incus_certificates.go
client/interfaces.go
cmd/incus/config_trust.go
internal/server/network/driver_macvlan.go

Resolves #1908.
Adds server-side filtering for the `incus config trust list` command. Updated CLI List to use `GetCertificatesWithFilter`. Did not update CLI List to use a `GetAllProjectCertificatesWithFilter` function because there is not an existing `GetCertificatesAllProjects` function.

Add server-side filtering for `incus config trust list`

---

doc/config_options.txt
doc/reference/network_sriov.md
internal/server/metadata/configuration.json
internal/server/network/driver_sriov.go

Resolves #1796 
Please let me know if any of the formatting is off. Thank you!

Port sriov network documentation to gendoc

---

internal/server/firewall/drivers/drivers_nftables_templates.go

Before:
```
sudo nft list ruleset
table inet incus {
...................
chain in.incusbr0 {
type filter hook input priority filter; policy accept;
iifname "incusbr0" tcp dport 53 accept
iifname "incusbr0" udp dport 53 accept
iifname "incusbr0" icmp type { destination-unreachable, time-exceeded, parameter-problem } accept
iifname "incusbr0" udp dport 67 accept
iifname "incusbr0" icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-solicit, nd-neighbor-solicit, nd-neighbor-advert, mld2-listener-report } accept
iifname "incusbr0" udp dport 547 accept
}
chain out.incusbr0 {
type filter hook output priority filter; policy accept;
oifname "incusbr0" tcp sport 53 accept
oifname "incusbr0" udp sport 53 accept
oifname "incusbr0" icmp type { …
```

incusd/firewall/nftables: disable UDP checksum validation for packets on bridged network

---

cmd/incusd/main_forknet.go

This PR addresses #1869
The main differences between nclient4 and nclient6 is that:
- nclient6 does not have a Lease struct, but rather works with dhcpv6.Message (the final Reply in the Solicit -> Advertisement -> Request -> Reply conversation)
- It doesn't seem like router information is provided in the Reply, so that's not added in the network configuration
- There is no Renew() function in nclient6 like there is in nclient4, so a Renew message is manually created and sent

Implement stateful DHCPv6

---

cmd/incus/remote.go
po/de.po
po/es.po
po/fr.po
po/id.po
po/incus.pot
po/it.po
po/ja.po
po/nb_NO.po
po/nl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/ta.po
po/zh_Hans.po
po/zh_Hant.po

This PR adds two new CLI subcommands under `incus remote`:
- `get-client-certificate`: Prints the client certificate in PEM format.
- `get-client-token`: Generates a JWT using the existing client certificate and private key.
These commands might replace the tls2jwt test tool, improve certificate discoverability. Hope that the format and code is good.
Closes #2010
Signed-off-by: stoven2k17 <stoven2k17@gmail.com>

incus/remote: Add "get-client-certificate" and "get-client-token"

---

cmd/incus-migrate/main_migrate.go
cmd/incus-migrate/migrate_instance.go
cmd/incus-migrate/migrate_ova.go

1. Added support for importing virtual machines from `.ova` files.
2. Made it possible to change the storage pool for additional disks.
3. CPU and memory configuration is now automatically extracted from the `.ova` file.
Closes: #1906

Add support for .OVA import

---

internal/server/instance/drivers/driver_lxc.go

The function inheritInitPidFd should only return the file descriptor, it is the caller's responsibility to determine the fdnr to pass to a subprocess.
I also refactored a few adjacent lines to hopefully improve readability, if desired I'll revert those or put them in a separate PR.

incusd/instance/lxc: Refactor inheritInitPidFd

---

shared/api/error.go
shared/api/metadata.go
shared/cliconfig/keepalive.go
shared/cliconfig/remote.go
shared/idmap/set.go
shared/idmap/set_linux.go
shared/ioprogress/tracker.go
shared/osarch/architectures.go
shared/subprocess/run.go
test/mini-oidc/storage/storage.go

Using more modern features of Go, such as:
- conditional assignment -> built-in min or max in go1.21,
- sort.Slice -> slices.Sort in go1.21,
- loop assign map -> maps.Copy in go1.21,
- []byte(fmt.Sprintf...) -> fmt.Appendf(nil,...) in go1.19,
- strings.HasPrefix / strings.TrimPrefix -> strings.CutPrefix in go1.20

Simplify code by using modern constructs

---

cmd/incusd/main_forkproxy.go
internal/server/device/proxy.go
test/suites/container_devices_proxy.sh

This was a copy-paste error introduced in commit https://github.com/lxc/incus/commit/4494bad12c572d069042cf169aa07d8fd82f4b3b
("incusd/main_forkproxy: Join all namespaces at once"). The net result
was that container-binding proxy devices with a unix listener would be
in the wrong mount namespace and the unix socket would accidentally be
created on the host.
Fixes: https://github.com/lxc/incus/commit/4494bad12c572d069042cf169aa07d8fd82f4b3b ("incusd/main_forkproxy: Join all namespaces at once")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

incusd/forkproxy: join the correct mntns for listen

---

cmd/incus-migrate/main_migrate.go
cmd/incus-migrate/migrate_instance.go
cmd/incus-migrate/migrate_ova.go
cmd/incus-migrate/migrate_volume.go

```
sudo ~/go/bin/incus-migrate
The local Incus server is the target [default=yes]:
Want to specify cluster target server? [default=no]: yes
Please provide name of cluster target server [default=none]: incus-svr1
What would you like to create?
1) Container
2) Virtual Machine
3) Virtual Machine (from .ova)
4) Custom Volume
Please enter the number of your choice:
```
**What was changed?**
Changes or issue https://github.com/lxc/incus/issues/2094 
**Tests Done**
build complete fine
Applied `incus-migrate` on test system and confirmed that prompt is made and validates if server is clustered

incus-migrate: prompt for cluster target

---

go.mod
go.sum
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/instance/drivers/qmp/qmp.go
internal/server/instance/drivers/qmp/qmp_test.go

`digitalocean/go-qemu/qmp` depends on `digitalocean/go-qemu` and `digitalocean/go-libvirt` as well, incus does not use anything related with go-libvrit, and the qmp part less maintaining, and do not associate response id with command id. So remove it.

Use our own QMP monitor

---

internal/linux/filesystem.go
shared/archive/archive.go

NFS4v2 supports user.xattr, and can be used with Incus via the dir driver, but image unpacking will fail when the container image uses non-user xattrs such as security.xattr
This fix will skip extraction of security.xattrs when extracting to an NFS hosted directory
The fix is not specific to the dir driver, and could benefit a future NFS driver too.
Closes #2148

incusd/storage: Fix squashfs unpacking to NFS destinations

---

internal/server/instance/drivers/driver_common.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go

Currently, the `volatile.cpu.nodes` value is only set when `limits.cpu.nodes` is set to `balanced`. In all other cases, `volatile.cpu.nodes` remains unchanged. This can be confusing, as it may lead to situations where `volatile.cpu.nodes` and `limits.cpu.nodes` contain different numeric values
Closes: #2121

Clear the "volatile.cpu.nodes" if needed

---

.vscode/launch.json

The Visual Studio Code editor has the ability to attach to or launch golang binaries for interactive debugging, with variable inspection and breakpoints
The launch.json file adds the following menu entries to the "Run and Debug" menu in VS Code
- Attach to Incusd
- Launch Incusd
- Launch Incusd --debug
The first menu will allow the user to select a running incusd instance to attach the VS Code Go Delve debugger to.
The other two options will launch the most recently built incusd, with or without the --debug option, allowing live debugging in the editor with breakpoints
Assuming incusd is built into the ~/go/bin directory.

vscode: Add VSCode launch.json for incusd "Run and Debug" functionality

---

internal/server/instance/drivers/driver_common.go

When both `io.bus` and disk size are changed together, the device is removed and re-added. In contrast, when only the size is changed, `Update` is called, which in turn invokes `applyQuota` to adjust the disk size .
This change ensures that `Update` is also called for the root disk when it is removed and re-added, allowing the size change to be applied correctly.
Fixes: #2137

Allow updating root disk size and root io.bus simultaneously

---

cmd/incusd/instance_backup.go
cmd/incusd/storage_volumes_backup.go
doc/api-extensions.md
doc/rest-api.yaml
internal/server/backup/backup_common.go
internal/server/backup/backup_instance.go
internal/server/backup/backup_volume.go
internal/version/api.go
shared/api/instance_backup.go
shared/api/storage_pool_volume_backup.go

Extended backup APIs to support uploading instance and custom volume backups to an S3 bucket, deleting the local backup afterwards.

Allow for direct S3 push of instance and custom volume backups

---

internal/server/device/nic_physical.go

fixes #1735 
After checking if parent property points to a bridge network, we create and instantiate a bridged device which we use to call `Start()` and `Stop()`. 
Meaning we are using 'bridged' logic already implemented, avoiding attempts to attach the parent interface into the container namespace which was the cause of previous errors.
This is the log showing success in launching a container following [these steps](https://github.com/lxc/incus/issues/1735#issuecomment-2799170436) :
```
Name: c1
Description: 
Status: RUNNING
Type: container
Architecture: x86_64
PID: 270002
Created: 2025/05/20 22:48 UTC
Last Used: 2025/05/20 23:26 UTC
Started: 2025/05/20 23:26 UTC
Resources:
Processes: 10
CPU usage:
CPU usage (in seconds): 0
Memory usage:
Memory (current): 20.75MiB
Network usage:
eth0: …
```

Feature: Added support for "physical" interface with bridge as parent

---

internal/server/storage/drivers/driver_zfs_volumes.go
test/suites/storage_driver_zfs.sh

When creating a volume of type `VolumeTypeCustom` with the ZFS driver the `incus:content_type` user property
is used to capture the `ContentType`. When recovering the storage pool or the volume, this
`content_type` is used to disambiguate the volume if it is using `zfs.block_mode`.
Unfortunately, when cloning the volume using `zfs.clone_copy` mode the `content_type` is lost
and the filesystem block mode volumes are imported as block mode volumes instead.
The fix corrects by regenerating the content_type during the clone when it is still known.
A test has been added to storage_driver_zfs.sh which reproduces the issue, and confirms the fix.

incusd/storage/zfs: Fix missing incus:content_type after cloning a custom volume

---

internal/server/firewall/drivers/drivers_nftables_templates.go

This fixes a couple of recent regressions (Incus 6.12 and 6.13) in how isolation rules are applied when combined with ACLs. Those specifically affect environments using `nftables` and `bridge` networking alongside the aforementioned isolation rules.
Thanks to Olivier BAL-PETRE of ANSSI (French Cybersecurity Agency) for reporting those and providing fixes for both issues!
Relevant security issues:
- CVE-2025-52890 (GHSA-p7fw-vjjm-2rwp)
- CVE-2025-52889 (GHSA-9q7c-qmhm-jv86)

Fix security issue due to rule ordering in nftables (ACLs + isolation)

---

internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go

We've seen a number of cases where we're racing the LVM tools or udev depending on distros and LVM config, so let's just serialize things on our end.

incusd/storage/lvm: Avoid concurrent activation/deactivation

---

cmd/incusd/main_forknet.go
internal/server/device/device_utils_network.go
internal/server/device/nic_bridged.go
internal/server/device/nic_ipvlan.go
internal/server/device/nic_routed.go
internal/server/ip/addr.go
internal/server/ip/class.go
internal/server/ip/filter.go
internal/server/ip/init.go
internal/server/ip/link.go
internal/server/ip/link_bridge.go
internal/server/ip/link_dummy.go
internal/server/ip/link_gretap.go
internal/server/ip/link_macvlan.go
internal/server/ip/link_macvtap.go
internal/server/ip/link_veth.go
internal/server/ip/link_vlan.go
internal/server/ip/link_vxlan.go
internal/server/ip/neigh.go
internal/server/ip/neigh_proxy.go
internal/server/ip/qdisc.go
internal/server/ip/qdisc_htb.go
internal/server/ip/qdisc_ingress.go
internal/server/ip/route.go
internal/server/ip/tuntap.go
internal/server/ip/utils.go
internal/server/ip/vdpa.go
internal/server/network/driver_bridge.go
internal/server/network/driver_ovn.go

See #1978 
This is still WIP, the PR at this time is mainly for running the CI. Feedback is very welcome though, especially on the non-trivial TODOs.

Use netlink instead of calling iproute2 commands

---

shared/idmap/shift_linux.go

This is typically ACLs that were set from outside of the containers or that have already been shifted. That -1 value would cause the ACL calls to fail, leading to a partly shifted container.

shared/idmap: Skip ACLs that are out of range

---

internal/server/storage/drivers/driver_lvm.go
internal/server/storage/drivers/driver_lvm_utils.go
internal/server/storage/drivers/driver_lvm_volumes.go

The /dev/mapper or /dev/VG/LV paths can occasionally be racy and so can be dangerous to use. Instead wait until the LV is activated, then get its major and minor from LVM and access it through the /dev/dm-X path instead.

incusd/storage/lvm: Don't rely on udev paths

---

cmd/incus-agent/dev_incus.go
cmd/incus-agent/operations.go
cmd/incus-agent/server.go

Since Go 1.22, we have the ability to create a request multiplexer using `http.ServeMux` with native libraries. This makes the [`gorilla/mux`](https://github.com/gorilla/mux) library obsolete (which also hasn't received any new commits for over a year now).
This PR removes usage of `gorilla/mux` for the `incus_agent` as a start. I do think it would be a wise decision to adopt this for all usages of it in this repository eventually.

cmd/incus_agent: Replace gorilla/mux with http.ServeMux

---

client/incus.go

This PR fixes formatting for string passed to `fmt.Errorf`.  This is inline with the recent golang 1.24 changes to its printf analyzer.  
I am one of the package maintainers for Fedora, incus fails our go vet checks due to this.

Fixed non-constant format string in call to fmt.Errorf

---

cmd/incusd/api_cluster.go

See https://github.com/FuturFusion/operations-center/pull/136#issuecomment-3051604162 for details.
I am pretty sure, that we need the fix from the first commit. The second commit might be debatable.

Ensure usage of server address from the join request

---

internal/server/ip/link.go
internal/server/ip/link_bridge.go
internal/server/ip/link_dummy.go
internal/server/ip/link_gretap.go
internal/server/ip/link_macvlan.go
internal/server/ip/link_macvtap.go
internal/server/ip/link_veth.go
internal/server/ip/link_vlan.go
internal/server/ip/link_vxlan.go

The `ALLMULTI` flag is not sent on device creation, so we need to set it afterwards.

incusd/ip: fix allmulti regression

---

internal/server/storage/drivers/generic_vfs.go

Closes: #2290
Not a huge fan of the solution, as it leads to code duplication with `MountPath`. Some refactoring may be worth it, LMK if it’s something you’d like me to look at.

incusd/storage: Fix ISO renaming

---

doc/api-extensions.md
doc/config_options.txt
internal/server/device/config/device_runconfig.go
internal/server/device/disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/driver_qemu_metrics.go
internal/server/instance/drivers/qmp/commands.go
internal/server/instance/drivers/qmp/monitor.go
internal/server/metadata/configuration.json
internal/version/api.go

This PR is not 100% ready. I’d like to discuss 2 things:
- Whether the attached/detached logic can stay as is, or should only concern CD-ROM drives (cf. TODO);
- Whether the attached/detached logic should be emulated like a full/empty CD-ROM tray, or (as it’s currently done in this PR) by simply removing/re-adding another CD-ROM drive.
Emulating an empty tray will require a bit more work, but can look a bit fancier to the user, actually seeing that the device is here but not the blockdev.
Closes #2093

Implement disk ejection

---

internal/server/instance/instance_utils.go

It's still usually a bad idea but there's no strong need to special case those vs the rest.

incusd/instance: Allow setting lxc.net config keys through raw.lxc

---

internal/server/ip/route.go

The route filter should apply to the output interface, not the input.

incusd/ip: Fix filtering of routes by interface

---

internal/server/instance/drivers/driver_qemu.go

This removes some duplicate logic, avoids failures when volumes come from profiles and adds special-handling for our internal volumes.

incusd/instance/qemu: Cleanup volume eject/detach logic

---

internal/server/scriptlet/auth/auth.go
internal/server/scriptlet/instance_placement.go
internal/server/scriptlet/load/load.go
internal/server/scriptlet/qemu.go
shared/scriptlet/marshal.go
shared/scriptlet/marshal_test.go
shared/scriptlet/utils.go

Moves the loading, marshalling, and validating logic for starlark scriptlets over to `shared/scriptlet` so that it can be used externally.

Move scriptlet utils to `shared/scriptlet`

---

cmd/incus-agent/os_linux.go
doc/config_options.txt
internal/instance/config.go
internal/server/device/disk.go
internal/server/instance/drivers/driver_lxc.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/instance_interface.go
internal/server/metadata/configuration.json

Bugs solved:
* Typing regressions caused by #1531
* Non-hot-unpluggable pre-boot virtiofs shares (Closes: #2323)
* 9p post-boot shares being wrongfully mounted as virtiofs
* Useless checks probably caused by confusion because `FSType=9p` server-side even in virtiofs shares (note that it’s different agent-side)
Additional actions:
* Remove pre-boot virtiofs logic
* Remove dual virtiofs+9p logic, enforcing a **single** mount type
* Make the agent a little dumber on path mounts (removing a virtiofs dmesg error when mounting 9p-only shares)
Future directions (to discuss here):
* Maybe add more intelligence to disable virtiofs if `image.os` and related keys match a house-tailored heuristic?
* Clarify `FSType=9p` into `FSType=share` or something like that?
* (more globally) Actually restrict …

Fixes for virtiofs and 9p shares

---

internal/server/apparmor/apparmor.go
internal/server/apparmor/instance.go
internal/server/apparmor/instance_lxc.profile.go

The userns feature can be used without the abi bump and the abi bump is causing other problematic side effects (breaking Docker in some cases).

incusd/apparmor: Don't use abi4.0

---

doc/metrics.md

Typo: Existing documentation has
>  "the project param is are provided"
I was reading this page and this help question: https://discuss.linuxcontainers.org/t/problem-with-incus-prometheus-and-multiple-projects/24226 . I was similarly confused by the documentation as an incus-metrics newbie. So in fixing the typo I also changed the note to explicitly state that if you don't use the project param then you get the default project or all projects.
Todo: Add how to define the default project?

Fix typo and add clarity for project param

---

cmd/incusd/main_forknet.go
internal/server/ip/route.go

**Problem**
When multiple DHCP clients attempt to install an IPv4 default route into the main table, netlink.RouteAdd can fail with EEXIST. This leads to noisy errors and nondeterministic behavior regarding which interface "owns" the default route.
**Summary of changes**
1. internal/server/ip:
- Made Route.List device-optional: when DevName is empty or unresolved, the OIF filter is cleared and routes across all devices are returned.
- Introduced a single builder netlinkRoute(mode) to construct netlink.Route for both apply (add/replace/delete) and query (list) paths.
2. incus/dhcp (DHCPv4 path in main_forknet.go):
- Introduce a policy to keep a single default route in the main table, owned by the lexicographically smallest interface name among candidates.
- Inspect current main table …

incus/dhcp: default routes and multiple DHCP clients for OCI containers

---

internal/server/network/network_utils.go

The current logic is incorrect. If any instance meets the condition `instNetworkProject != networkProjectName`, the function stops execution without processing the other instances, which may also satisfy this condition. As a result, not all instances are processed and some may be skipped.

Fix logic for UsedByInstanceDevices

---

cmd/incusd/patches.go
internal/server/network/acl/acl_ovn.go
internal/server/network/driver_ovn.go
internal/server/network/ovn/ovn_nb_actions.go

This change adds support for prioritizing allow rules when the default policy for a network or interface is set to allow. By default, the policy is reject, so reject rules have higher priority.
To implement this, the original single port group was replaced with four separate port groups:
- Ingress (allow-first)
- Ingress (reject-first)
- Egress (allow-first)
- Egress (reject-first)
These groups store rules in the required order, allowing correct rule evaluation based on the default policy.
Fixes: #1833

Add directional port groups with allow/reject priority based on default policy

---

internal/server/network/acl/acl_ovn.go
internal/server/network/driver_ovn.go

#2372 introduced a bug that causes incorrect behavior when an ACL name is used as a source.  
Previously, the match expression was generated in the following format:
```
(outport == @incus_acl13_ingress_reversed) &&
(inport == @incus_acl13_ingress ||
inport == @incus_acl13_ingress_reversed ||
inport == @incus_acl13_egress ||
inport == @incus_acl13_egress_reversed)
```
However, this fails if any of the port groups are empty, since OVN does not copy empty port groups between the Northbound and Southbound databases. This results in a parsing error in the match expression.  
This PR introduces a new port group that aggregates all ports assigned to the ACL, ensuring the match expression remains valid

Fix behavior when ACL name is used as match source

---

test/suites/migration.sh
test/suites/storage_driver_zfs.sh

xfsprogs in Ubuntu 24.04 seems to have some weird initialization issues. Remove the package to skip those tests. We still have daily tests validating XFS anyway.

github: Remove XFS tools

---

doc/architectures.md
doc/environment.md
doc/explanation/containers_and_vms.md
doc/explanation/security.md
doc/explanation/storage.md
doc/howto/network_acls.md
doc/howto/network_address_sets.md
doc/howto/network_forwards.md
doc/howto/network_integrations.md
doc/howto/network_load_balancers.md
doc/howto/network_ovn_peers.md
doc/howto/network_zones.md
doc/reference/server_settings.md
doc/reference/storage_btrfs.md
doc/reference/storage_ceph.md
doc/reference/storage_cephfs.md
doc/reference/storage_cephobject.md
doc/reference/storage_dir.md
doc/reference/storage_drivers.md
doc/reference/storage_linstor.md
doc/reference/storage_lvm.md
doc/reference/storage_truenas.md
doc/reference/storage_zfs.md
doc/rest-api.md

* MD055 Table row doesn't begin/end with pipes
* MD057 Table has missing or invalid header separation (second row)
General alignment of the columns.

docs: Fix markdown linting issues for tables

---

client/oci_images.go

Enables specifying OCI images as `IMAGE:TAG@HASH`
Previously, attempting to launch an OCI instance with:
```bash
$ incus launch docker:kindest/node:v1.33.0@sha256:91e9ed777db80279c22d1d1068c091b899b2078506e4a0f797fbf6e397c0b0b2 test
Error: Failed instance creation: Image not found
```
and incus logs printed 
```
Sep 06 17:50:37 zs-builder incusd[671766]: time="2025-09-06T17:50:37Z" level=debug msg="Error getting image alias" name="kindest/node:v1.33.0@sha256:91e9ed777db80279c22d1d1068c091b899b2078506e4a0f797fbf6e397c0b0b2" stderr="Failed to run: skopeo inspect docker://kindest/node:v1.33.0@sha256:91e9ed777db80279c22d1d1068c091b899b2078506e4a0f797fbf6e397c0b0b2: exit status 1 (time=\"2025-09-06T17:50:37Z\" level=fatal msg=\"Error parsing image name …
```

client/oci: Allow OCI image names with a pinned hash

---

shared/tls/tls.go

We added this to allow bypass of expired cert verification errors, but it causes issues with cert chains and pre-existing, older certs.

shared/tls: Remove tls.Config.Time override

---

internal/server/network/driver_ovn.go
internal/server/network/driver_physical.go

- Updated OVN uplink and chassis detection logic to skip networks of type "physical" with parent set to "none".
- Ensured physical network driver setup permits parent="none" and checks interface existence accordingly.
- Nodes with physical uplinks that specify a valid parent (not "none") will participate in the OVN HA chassis group; nodes with parent="none" will be excluded.
- Behaviour tested by creating network with both parent=enp6s0 and parent=none on multiple nodes using Incus deploy.
- Only nodes with a valid physical uplink parent are added to the HA group, matching expected OVN behaviour.

incusd/network: Exclude physical networks with parent=none from OVN chassis enablement

---

internal/server/instance/drivers/driver_qemu.go

The latest virtio Windows drivers now include a signed vsock driver so let's re-enable the device.

incusd/instance/qemu: Re-enable vsock on Windows

---

shared/idmap/internal_linux.go

When parsing extended attributes, we may be getting EINVAL when run on ZFS.
This appears to be when dealing with ZFS namespaced xattrs and despite being real root with all capabilities, there appears to be no way to read or even clear those attributes.
So instead of crashing mid-shift, let's just log them and move on.

shared/idmap: Skip xattrs on EINVAL

---

client/connection.go
client/util.go
internal/server/cluster/connect.go
internal/server/cluster/gateway.go
internal/server/cluster/heartbeat.go
internal/server/cluster/tls.go

Occasionally a server will have its certificate expire.
This is particularly common when using ACME/Let's Encrypt and somehow failing renewal.
In that scenario, the cluster should keep operating mostly normally until the user updates the certificate with a newer one.
Prior to this, the cluster would fail all internal connections and would completely deadlock should servers get restarted, more importantly, the API used to update the certificate would also fail in that scenario.
Closes #2498

Rework cluster internal certificate validation

---

.golangci.yml
doc/rest-api.yaml
internal/filter/value.go
internal/server/db/storage_pools_test.go
shared/api/cluster.go
shared/api/config.go
shared/api/config_test.go
shared/api/instance.go
shared/api/instance_snapshot.go
shared/api/network.go
shared/api/network_acl.go
shared/api/network_address_set.go
shared/api/network_forward.go
shared/api/network_integration.go
shared/api/network_load_balancer.go
shared/api/network_peer.go
shared/api/network_zone.go
shared/api/profile.go
shared/api/project.go
shared/api/server.go
shared/api/storage_pool.go
shared/api/storage_pool_bucket.go
shared/api/storage_pool_volume.go
shared/api/storage_pool_volume_snapshot.go

If we agree to continue with this approach, the same might be applied to the `map[string]map[string]string` used for devices.
Continuation of #2940

Replace map[string]string with ConfigMap for more user friendly handling of bool and numbers (with defaults)

---

doc/howto/storage_backup_volume.md

The current command doesn't work for me on incus 6.16.  The error message is `Error: Invalid storage volume "<volume name>/<snapshot name>"`.  It seems like the command should be `storage volume snapshot delete` rather than `storage volume delete` for a snapshot.
Please correct me if I'm wrong.

Change snapshot deletion command to `storage volume snapshot delete`

---

internal/server/cluster/connect.go

Similar to later communications, don't go through a proxy as that breaks TLS authentication and causes a join failure.

incusd/cluster: Don't use proxy when joining

---

internal/server/device/config/device_runconfig.go
internal/server/device/disk.go
internal/server/instance/drivers/driver_qemu.go
internal/server/instance/drivers/qmp/commands.go

When I initially worked on #2282, I made a few assumptions that ended up invalid and a few design choices that changed mid-PR. This PR removes all handling of the attached status (except during ejection) by the QEMU driver, to handle it as early as possible, like in #2530. #2531 turned out to be just the tip of the iceberg, sorry for the oversight.

Cleanup disk attached logic

---

cmd/incusd/instance_console.go

This will cause the remote client to get disconnected immediately rather than on the next websocket message exchange.

incusd/console: Close remote connection on console disconnect
